import { MeReportSkills } from './types'
import { defaultError } from '@/service/auth'
import { createUrl } from '@/lib/url-utils'

const urls = { skills: '/me/reports/skills/', languages: '/me/reports/languages/' }

export const fetchReportSkills = async (token: string, params) => {
  // const res = await api(token, urls.skills, {}, params)
  // return res.json()
  //TODO: change to fetch
  console.log('fetch', { token, params })
  return Promise.resolve(skillsData)
}

export const exportReportSkills = (params): string => createUrl(urls.skills, params)

export const fetchReportLanguages = async (token: string) => {
  const res = await api(token, urls.languages)
  return res.json()
}

export const exportReportLanguages = (params): string => createUrl(urls.languages, params)

const api = async (
  token: string,
  url: RequestInfo | URL,
  init?: RequestInit,
  params?: URLSearchParams
): Promise<Response> => {
  const apiUrl = createUrl(url, params)
  const res: Response = await fetch(createUrl(apiUrl, params), {
    ...init,
    headers: { ...init.headers, Authorization: `Token ${token}` }
  })
  if (res.ok) return res
  try {
    const { detail } = await res.json()
    if (detail) throw new Error(detail)
  } catch (e) {}
  throw new Error(defaultError)
}

//TODO: Delete this
const skillsData: MeReportSkills = {
  page: 1,
  per_page: 10,
  total: 100,
  total_pages: 10,
  data: [
    {
      name: 'Skill 1',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 2',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 3',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 4',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 5',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 6',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 7',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 8',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 9',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 10',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 11',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 12',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 13',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 14',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 15',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 16',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 17',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 18',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 19',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 20',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 21',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 22',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 23',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 24',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 25',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 26',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 27',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 28',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 29',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 30',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 31',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 32',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 33',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 34',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 35',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 36',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 37',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 38',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 39',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 40',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 41',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 42',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 43',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 44',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 45',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 46',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 47',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 48',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 49',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 50',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 51',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 52',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 53',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 54',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 55',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 56',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 57',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 58',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 59',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 60',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 61',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 62',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 63',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 64',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 65',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 66',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 67',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 68',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 69',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 70',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 71',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 72',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 73',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 74',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 75',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 76',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 77',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 78',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 79',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 80',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 81',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 82',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 83',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 84',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 85',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 86',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 87',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 88',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 89',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 90',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 91',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 92',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 93',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 94',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 95',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 96',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 97',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 98',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 99',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    },
    {
      name: 'Skill 100',
      skill_label: '1 (1%)',
      skill_value_total: 1,
      skill_value_percentage: 1,
      skills_develop_label: '1 (1%)',
      skills_develop_value_total: 1,
      skills_develop_value_percentage: 1,
      beginner_label: '1 (1%)',
      advanced_beginner_label: '1 (1%)',
      competent_label: '1 (1%)',
      proficient_label: '1 (1%)',
      expert_label: '1 (1%)'
    }
  ]
}
