version: '3'

volumes:
  organogram_postgres_data: {}
  ellandi_postgres_data: {}
  minio_data: {}

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost/api
        API_HOST: http://api:8000
    image: nginx_main
    depends_on:
      - api
    env_file:
      - ./envs/nginx
    ports:
      - "80:80"

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      args:
        GIT_SHA: ""
    image: ellandi_api
    depends_on:
      - ellandi-db
    env_file:
      - ./envs/api
    volumes:
      - ./:/app/:z
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        NODE_ENV: development
        NEXT_PUBLIC_API_URL: http://localhost:8000/api
        GIT_SHA: ""
    image: ellandi_web
    env_file:
      - ./envs/web
    environment:
      - NODE_ENV
    ports:
      - "3000:3000"

  organogram:
    build:
      context: .
      dockerfile: ./docker/organogram/Dockerfile
    image: organogram
    depends_on:
      - organogram-db
      - minio
    env_file:
      - ./envs/organogram
    volumes:
      - ./:/app/:z
    ports:
      - "8001:8001"

  ellandi-db:
    image: postgres:13
    container_name: ellandi_postgres
    volumes:
      - ellandi_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./envs/api
    expose:
      - "5432"

  organogram-db:
    image: postgres:13
    container_name: organogram_postgres
    volumes:
      - organogram_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./envs/organogram
    expose:
      - "5432"

  minio:
    image: minio/minio:RELEASE.2021-06-14T01-29-23Z
    container_name: organogram_minio
    volumes:
      - minio_data:/data
    env_file:
      - ./envs/minio
    ports:
      - "9000:9000"
    command: server /data

  tests-api:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
      args:
        APP: api
        MODULE: ellandi
    image: tests_api
    env_file:
      - ./envs/tests
    profiles:
      - testing

  tests-organogram:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
      args:
        APP: organogram
        MODULE: organogram
    image: tests_organogram
    env_file:
      - ./envs/tests
    profiles:
      - testing

  requirements:
    image: python:3.8-buster
    profiles:
      - utils
    volumes:
      - ./:/app/:z
