version: '3'

volumes:
  local_postgres_data: {}
  minio_data: {}

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: ellandi_api
    depends_on:
      - ellandi-db
    env_file:
      - ./.envs/api
    volumes:
      - ./:/app/:z
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        NODE_ENV: development
        NEXT_PUBLIC_API_URL: http://localhost:8000
    image: ellandi_web
    env_file:
      - ./.envs/web
    environment:
      - NODE_ENV
    ports:
      - "3000:3000"

  organogram:
    build:
      context: .
      dockerfile: ./docker/organogram/Dockerfile
    image: organogram
    depends_on:
      - organogram-db
      - minio
    env_file:
      - ./.envs/organogram
    volumes:
      - ./:/app/:z
    ports:
      - "8001:8001"

  ellandi-db:
    image: postgres:13
    container_name: ellandi_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/api
    expose:
      - "5432"
    profiles:
      - services

  organogram-db:
    image: postgres:13
    container_name: organogram_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/organogram
    expose:
      - "5432"
    profiles:
      - services

  minio:
    image: minio/minio:RELEASE.2021-06-14T01-29-23Z
    container_name: organogram_minio
    volumes:
      - minio_data:/data
    env_file:
      - ./.envs/minio
    ports:
      - "9000:9000"
    command: server /data
    profiles:
      - services

  integration:
    build:
      context: .
      dockerfile: ./docker/integration/Dockerfile
    image: ellandi_integration
    depends_on:
      - web
    profiles:
      - testing

  tests-api:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
      args:
        APP: api
    image: tests_api
    env_file:
      - ./.envs/tests
    profiles:
      - testing

  tests-organogram:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
      args:
        APP: organogram
    image: tests_organogram
    env_file:
      - ./.envs/tests
    profiles:
      - testing

  requirements:
    image: python:3.8-buster
    profiles:
      - utils
    volumes:
      - ./:/app/:z
