version: '3'

volumes:
  local_postgres_data: {}

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: ellandi_api
    depends_on:
      - postgres
    env_file:
      - ./.envs/api
      - ./.envs/postgres
    volumes:
      - ./:/app/:z
    ports:
      - "8000:8000"
    command: /start.sh

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: ellandi_web
    depends_on:
      - api
    volumes:
      - ./:/app/:z
    ports:
      - "3000:3000"
    command: npm run dev

  postgres:
    image: postgres:11
    container_name: ellandi_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/postgres
    ports:
      - "5432:5432"
