version: '3'

volumes:
  local_postgres_data: {}

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: ellandi_api
    depends_on:
      - postgres
    env_file:
      - ./.envs/api
      - ./.envs/postgres
    volumes:
      - ./:/app/:z
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: ellandi_web
    env_file:
      - ./.envs/web
    environment:
      - NODE_ENV
    volumes:
      - ./:/app/:z
      - '/app/web/node_modules'
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13
    container_name: ellandi_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/postgres
    ports:
      - "5432:5432"

  integration:
    build:
      context: .
      dockerfile: ./docker/integration/Dockerfile
    image: ellandi_integration
    depends_on:
      - web
    entrypoint: /entrypoint.sh
    profiles:
      - testing

  tests:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
    image: ellandi_tests
    env_file:
      - ./.envs/tests
    profiles:
      - testing
