version: '3'

volumes:
  organogram_postgres_data: {}
  ellandi_postgres_data: {}
  minio_data: {}

services:
  api:
    build:
      args:
        NEXT_PUBLIC_API_URL: http://api:8000

  integration:
    build:
      context: .
      dockerfile: ./docker/integration/Dockerfile
    image: ellandi_integration
    volumes:
      - ./:/app/:z
    depends_on:
      - api
    profiles:
      - testing
