# Generated by Django 3.2.14 on 2022-07-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_loaddata_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=4095, null=True),
        ),
    ]
