# Generated by Django 3.2.14 on 2022-07-20 10:20

from django.db import migrations, models

import organogram.registration.models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_loaddata_fixtures"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                storage=organogram.registration.models.PhotoStorage(),
                upload_to=organogram.registration.models.photo_upload_to,
            ),
        ),
    ]
