# Generated by Django 3.2.14 on 2022-07-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_auto_20220719_1959"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sub_unit",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
