# Generated by Django 3.2.14 on 2022-07-20 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_user_biography"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="primary_profession",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="registration.profession",
            ),
        ),
    ]
