# Generated by Django 3.2.14 on 2022-07-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_user_photo"),
        ("registration", "0004_user_primary_profession"),
    ]

    operations = []
