# Generated by Django 3.2.14 on 2022-07-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_user_sub_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
