# Generated by Django 3.2.14 on 2022-07-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_merge_0003_user_photo_0004_user_primary_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organogram_id',
            field=models.CharField(blank=True, max_length=4095, null=True),
        ),
    ]
