# Generated by Django 3.2.14 on 2022-07-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_user_organogram_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("sub_unit", models.CharField(max_length=255)),
                ("business_unit", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("name", "sub_unit", "business_unit")},
            },
        ),
    ]
