# Generated by Django 3.2.14 on 2022-07-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_user_organogram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_unit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
    ]
