# Generated by Django 3.2.14 on 2022-07-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_unit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
    ]
