# Generated by Django 3.2.14 on 2022-07-25 13:59
from django.core.management import call_command
from django.db import migrations


def load_teams(apps, schema_editor):
    fixture_file = "dropdown/teams.json"
    call_command("loaddata", fixture_file, app_label="registration", ignorenonexistent=True)


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_auto_20220726_1222"),
    ]

    operations = [migrations.RunPython(load_teams)]
