# Generated by Django 3.2.14 on 2022-07-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_add_initial_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
    ]
