# Generated by Django 3.2.14 on 2022-07-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0009_alter_team_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={},
        ),
    ]
