# Generated by Django 3.2.14 on 2022-07-12 10:33
import csv

from django.db import migrations


def populate_teams(apps, schema_editor):
    Team = apps.get_model("registration", "Team")
    teams = set()
    filename = "ellandi/registration/migrations/0010_initial_teams.csv"

    with open(filename, mode="r") as csv_file:
        csv_reader = csv.DictReader(csv_file)
        for row in csv_reader:
            team = Team(name = row["team"], sub_unit = row["sub_unit"], business_unit = row["business_unit"])
            teams.add(team)
    Team.objects.bulk_create(teams)


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0009_user_team"),
    ]

    operations = [migrations.RunPython(populate_teams)]
