# Generated by Django 3.2.14 on 2022-07-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_add_initial_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
