# Generated by Django 3.2.14 on 2022-07-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0010_alter_team_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["name"]},
        ),
    ]
