# Generated by Django 3.2.13 on 2022-06-20 12:37

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0014_auto_20220620_1129"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLanguage",
            fields=[
                ("created_at", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("modified_at", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("language", models.CharField(blank=True, max_length=127)),
                ("level", models.CharField(blank=True, max_length=127)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "language")},
            },
        ),
    ]
