# Generated by Django 3.2.13 on 2022-06-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0018_populate_language_skill_levels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
    ]
