# Generated by Django 3.2.13 on 2022-06-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0020_userlanguage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profession",
            field=models.ManyToManyField(blank=True, to="registration.Profession"),
        ),
    ]
