# Generated by Django 3.2.13 on 2022-07-05 20:09

from django.db import migrations, models

import organogram.registration.models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0022_alter_userlanguage_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(default=organogram.registration.models.now, editable=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="modified_at",
            field=models.DateTimeField(default=organogram.registration.models.now, editable=False),
        ),
        migrations.AlterField(
            model_name="userlanguage",
            name="created_at",
            field=models.DateTimeField(default=organogram.registration.models.now, editable=False),
        ),
        migrations.AlterField(
            model_name="userlanguage",
            name="modified_at",
            field=models.DateTimeField(default=organogram.registration.models.now, editable=False),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="created_at",
            field=models.DateTimeField(default=organogram.registration.models.now, editable=False),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="modified_at",
            field=models.DateTimeField(default=organogram.registration.models.now, editable=False),
        ),
        migrations.AlterField(
            model_name="weberror",
            name="created_at",
            field=models.DateTimeField(default=organogram.registration.models.now, editable=False),
        ),
        migrations.AlterField(
            model_name="weberror",
            name="modified_at",
            field=models.DateTimeField(default=organogram.registration.models.now, editable=False),
        ),
    ]
