# Generated by Django 3.2.13 on 2022-06-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0022_alter_userlanguage_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSalt",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True, verbose_name="email"
                    ),
                ),
                ("salt", models.BinaryField(max_length=16)),
            ],
        ),
    ]
