# Generated by Django 3.2.13 on 2022-07-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0023_usersalt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserSalt",
            new_name="EmailSalt",
        ),
    ]
