# Generated by Django 3.2.14 on 2022-07-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0024_delete_weberror"),
    ]

    operations = [
        migrations.AddField(
            model_name="languageskilllevel",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
    ]
