# Generated by Django 3.2.14 on 2022-07-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0025_merge_20220707_1540"),
        ("registration", "0027_country"),
    ]

    operations = []
