# Generated by Django 3.2.14 on 2022-07-12 10:33

from django.db import migrations
from django.utils.text import slugify


def populate_countries(apps, schema_editor):
    Country = apps.get_model("registration", "Country")
    countries = []
    filename = "organogram/registration/migrations/0029_FCDO-geographical-names-index-Feb22.txt"
    with open(filename) as file:
        for line in file:
            name = line.strip()
            country = Country(name=name, slug=slugify(name))
            countries.append(country)
        Country.objects.bulk_create(countries)


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0028_merge_0025_merge_20220707_1540_0027_country"),
    ]

    operations = [migrations.RunPython(populate_countries)]
