# Generated by Django 3.2.14 on 2022-07-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0030_amend_dropdowns"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
    ]
