---
applications:
- name: ellandi-api
  services:
    - ellandi-postgres
  routes:
    - route: ellandi-api.london.cloudapps.digital
      protocol: http1
  processes:
    - type: web
      instances: 1
      memory: 512M
      disk_quota: 1024M
      health-check-type: port
