---
applications:
- name: ellandi-prod
  services:
  - ellandi-postgres
  - scale-ellandi
  routes:
  - route: ellandi-prod.london.cloudapps.digital
    protocol: http1
  processes:
  - type: web
    instances: 1
    memory: 64M
    disk_quota: 2048M
    health-check-type: port
