---
applications:
- name: ellandi-api
  services:
  - ellandi-postgres
  - scale-ellandi-api
  routes:
  - route: ellandi-api.london.cloudapps.digital
    protocol: http1
  - route: ellandi-api.apps.internal
    protocol: http1
  processes:
  - type: web
    instances: 1
    memory: 1024M
    disk_quota: 8184M
    health-check-type: port
