---
applications:
  - name: ellandi-web
    env:
      NODE_ENV: production
    routes:
      - route: ellandi-web.london.cloudapps.digital
        protocol: http1
    processes:
      - type: web
        instances: 1
        memory: 512M
        disk_quota: 2048M
        health-check-type: port
