---
applications:
- name: digital-organogram
  services:
  - i-dot-ai-organogram-prod
  - organogram-postgres
  routes:
  - route: digital-organogram.london.cloudapps.digital
    protocol: http1
  processes:
  - type: web
    instances: 1
    memory: 256M
    disk_quota: 1024M
    health-check-type: port
