from ellandi.registration.utils import reverse_dict_lists

INITIAL_SKILLS = set(
    [
        "Accessibility",
        "Agile and lean practices",
        "Agile working",
        "Agile working (content design)",
        "Analysis",
        "Analysis and synthesis",
        "Analytical and problem-solving",
        "Asset and configuration management",
        "Availability and capacity management",
        "Bridging the gap between the technical and non-technical",
        "Business analysis",
        "Business analysis (IT operations)",
        "Business improvement process",
        "Business modelling",
        "Business process testing",
        "Change management",
        "Coding and scripting",
        "Commercial management",
        "Communicating analysis and insight",
        "Communicating information",
        "Communication skills",
        "Communication skills (data)",
        "Communication skills (security architect)",
        "Community collaboration",
        "Content concepts and prototyping",
        "Continual service improvement",
        "Continuity management",
        "Customer service management",
        "Cyber/security",
        "Data analysis and synthesis",
        "Data communication",
        "Data development process",
        "Data governance",
        "Data innovation",
        "Data integration design",
        "Data management",
        "Data modelling",
        "Data modelling, data cleansing and data enrichment",
        "Data standards",
        "Data visualisation",
        "DDaT perspective",
        "Design secure systems",
        "Digital perspective",
        "Enabling and informing risk-based decisions",
        "Enterprise and business architecture",
        "Evidence-based and context-based design",
        "Experience of using tools and software",
        "Experience of working within constraints",
        "Facilitating decisions and risks",
        "Financial management",
        "Financial ownership",
        "Functional testing",
        "Governance",
        "Governance and assurance",
        "Incident management",
        "Inclusive research",
        "Information security",
        "Innovation",
        "IT infrastructure",
        "IT infrastructure (network architect)",
        "Leadership and guidance",
        "Life-cycle perspective",
        "Logical and creative thinking",
        "Maintaining delivery momentum",
        "Making and guiding decisions",
        "Making the process work",
        "Metadata management",
        "Methods and tools",
        "Modern standards approach",
        "Non-functional testing",
        "Operational management",
        "Ownership and initiative",
        "Performance measurement",
        "Planning",
        "Problem management",
        "Problem ownership",
        "Problem resolution (data)",
        "Problem solving",
        "Product ownership",
        "Programming and build",
        "Programming and build (data engineering)",
        "Programming and build (software engineering)",
        "Project management",
        "Prototyping",
        "Prototyping in code",
        "Proven IT and mathematical",
        "Quality assurance, validation and data linkage",
        "Relationship management",
        "Requirements definition and management",
        "Research and innovation",
        "Research skills",
        "Service focus",
        "Service Management Framework knowledge",
        "Service reporting",
        "Service support",
        "Society and technology",
        "Specific security technology and understanding",
        "Stakeholder relationship management",
        "Stakeholder relationship management (content design)",
        "Statistical methods and data analysis",
        "Strategic insight",
        "Strategic ownership",
        "Strategic thinking",
        "Strategic thinking (content design)",
        "Strategic thinking (data architecture)",
        "Strategy",
        "Systems design",
        "Systems integration",
        "Systems integration (network architect)",
        "Team dynamics and collaboration",
        "Technical breadth",
        "Technical specialism",
        "Technical understanding",
        "Technical understanding (data engineering)",
        "Technical understanding (infrastructure engineer)",
        "Technical understanding (network architect)",
        "Technical understanding (performance analyst)",
        "Test analysis",
        "Testing",
        "Testing (business analysis)",
        "Troubleshooting and problem resolution",
        "Turning business problems into data design",
        "Turning business problems into technical design",
        "Understanding analysys across the product lifecycle",
        "Understanding constraints (performance analyst)",
        "Understanding security implications of transformation",
        "Understanding the whole context",
        "Undertaking analysis and providing insight",
        "User focus",
        "User focus (content design)",
        "User-centred analysis",
        "User-centred and agile practices",
        "User-centred content design",
        "Verification and validation of data and analysis",
        "Web performance optimisation",
    ]
)


NLP_DERIVED_SKILLS = set(
    [
        "Absence management",
        "access control",
        "accident reporting",
        "accuracy",
        "agile development  using continuous integration principle",
        "agile project management",
        "agile project management tools",
        "analysis",
        "assurance processes",
        "attendance management",
        "auditting",
        "aviation",
        "balancing quality and cost effectiveness",
        "behaviour change",
        "budget forecasting",
        "budget management",
        "building automated tests",
        "business architectures",
        "business cases",
        "business data",
        "business improvement",
        "business intelligence ",
        "business performance",
        "business planning",
        "calendar management",
        "capability development",
        "capacity management",
        "career development",
        "case management",
        "case management system",
        "certification standards",
        "change control management",
        "change management",
        "ci/cd pipelines",
        "climate change and energy policy",
        "clinical supervision",
        "cloud/ open source technologies",
        "coaching",
        "coaching and development",
        "coding",
        "coding languages (r, vba, sql, python, aws)",
        "collaboration",
        "commercial advice",
        "commercial awareness",
        "commercial capability",
        "commercial contract",
        "commercial negotiation",
        "commercial supplier management",
        "communicate threat assessment",
        "communicating risk",
        "communication",
        "communication skills (oral and written)",
        "communication systems",
        "communication technology",
        "communications",
        "communications and engagement",
        "compliance and quality systems",
        "compliance standards",
        "computer literacy",
        "conflict resolution",
        "content decisions",
        "content design",
        "continous improvement",
        "continuous delivery",
        "continuous improvement",
        "continuous improvement, personal-responsibility",
        "contract documentation",
        "contract management",
        "cost estimating",
        "cost management",
        "creative communication campaigns",
        "creative problem solving",
        "criminal case management",
        "criminal justice",
        "critical incident management",
        "cross cutting policy",
        "cross-team working",
        "cryptography",
        "cultural change",
        "culture change",
        "customer service",
        "customer support",
        "customer/stakeholder relations",
        "data",
        "data acquisition",
        "data analysis",
        "data backup and recovery",
        "data breach management",
        "data communication",
        "data flows",
        "data governance",
        "data informed decision making",
        "data literacy and communication",
        "data modelling",
        "data quality assurance",
        "data security",
        "data security and assurance",
        "data sharing agreements",
        "data streaming systems",
        "data visualisation",
        "decision making",
        "defining professional standards",
        "delivering behavioural interventions",
        "delivering technology change",
        "delivery",
        "dependency management",
        "design communication",
        "design governance",
        "develop customer relationships",
        "developing key performance indicator",
        "developing reporting",
        "diary management",
        "digital development",
        "digital literacy",
        "digital transformation",
        "disaster recovery",
        "document control",
        "document user specifications",
        "documentation management",
        "drafting papers",
        "economic growth policy",
        "editing",
        "editing and proofreading",
        "effective governance",
        "emerging cyber threats",
        "employee engagement",
        "employee relations",
        "employment law",
        "engagement strategy",
        "engineering practises",
        "ethical standards",
        "event planning",
        "evidence based decisions",
        "evidence based policy",
        "facility management",
        "fact finding",
        "family policy",
        "file management",
        "finance",
        "financial controls",
        "financial information",
        "financial management",
        "financial reporting",
        "financial risk",
        "fire service",
        "fiscal events",
        "formal teaching",
        "forward planning",
        "fraud policy",
        "future demand management",
        "gap analysis",
        "general administration",
        "generating documentation",
        "geographically dispersed team",
        "geospatial analysis",
        "good judgement",
        "governance",
        "governance progammes",
        "government accounting policy",
        "government housing",
        "habitat management",
        "handling data requests",
        "health data",
        "horizon scanning",
        "hr policy",
        "identify errors/ risks",
        "identifying risk",
        "immigration policy",
        "implementing solutions",
        "inbox management",
        "information asset management",
        "information governance",
        "information management",
        "information sharing",
        "innovation",
        "inspection protocols",
        "intelligence and analytical products",
        "intelligence flow",
        "internal stakeholder management",
        "international politics",
        "interpreting data",
        "investigations",
        "investments",
        "invoicing",
        "it development",
        "laboratory working practices",
        "leadership",
        "leadership coaching",
        "leadership/ lm",
        "leading a team",
        "leading change",
        "leading teams",
        "learning products",
        "legal advice",
        "legal training",
        "legislative complianced",
        "line management",
        "local policy",
        "logistics",
        "maintain communication",
        "maintaining office machinery",
        "maintaining safety standards",
        "maintenance",
        "manage budgets",
        "manage business relationships",
        "manage customer expectations",
        "manage ministerial correspondence",
        "manage project risk",
        "manage reputational risk",
        "manage software licenses",
        "management",
        "management information",
        "management system software",
        "managing challening situations",
        "managing clinical samples",
        "managing consulation responses",
        "managing data quality",
        "managing forecasting resources",
        "managing journalist relationships",
        "managing telephone enquiries",
        "maritime matters",
        "market research",
        "mathematical models",
        "meeting coordination",
        "meeting minutes",
        "mentoring",
        "microservices architectures",
        "military policy",
        "ministerial briefing",
        "ministerial correspondence",
        "molecular testing",
        "monitoring compliance",
        "multi-disciplinary team management",
        "navigate difficult conversations",
        "negotiation",
        "nuclear safety",
        "numeracy",
        "oil industry",
        "optimisation",
        "oral and written communication",
        "oral briefings",
        "oral communication",
        "oral presentations",
        "parliamentary government liaison",
        "parliamentary process",
        "performance data",
        "performance monitoring and alerting",
        "performance reporting",
        "personal credibility",
        "pesticide use",
        "photocopying & faxing",
        "planning",
        "planning ",
        "planning and scheduling",
        "planning multiple workstreams",
        "policy advice",
        "policy compliance framework",
        "policy development",
        "policy legislative change",
        "political awareness",
        "portfolio and progamme management",
        "preparing tribunal hearings",
        "presentation writing",
        "printing",
        "prioritisation",
        "prioritise",
        "prioritise effectively",
        "prioritise effectively, positions-constructively",
        "prioritising",
        "problem management",
        "problem solving",
        "process improvement",
        "process mapping",
        "procurement",
        "produce guidance documents",
        "producing witness statement",
        "product development",
        "product life cycle analysis",
        "productivity",
        "professional development",
        "programme design",
        "programme management",
        "project assurance",
        "project control and reporting",
        "project governance",
        "project management",
        "project management tools",
        "project plan",
        "project risk management",
        "prototyping",
        "provide assurance",
        "provide workflow management",
        "providing constructive challenge",
        "public relations",
        "public speaking and presentations",
        "python coding",
        "qualitative and quantitative analysis",
        "quality assurance",
        "quality control",
        "quick learner",
        "receipting and processing invoices",
        "record management",
        "recruitment",
        "relationship building",
        "relationship management",
        "report preparation",
        "report writing",
        "reporting governance",
        "reporting risk",
        "research grants and funding",
        "research presentation",
        "resilience",
        "resilient landscapes",
        "resource management",
        "resource management tools",
        "restful apis",
        "reverse engineer data models",
        "reviewing customer feedback",
        "risk assessment",
        "risk assessment documentation",
        "risk governance framework",
        "risk identification",
        "risk management",
        "risk monitoring",
        "running workshops",
        "scientific writing",
        "search engine optimisation",
        "secretariat",
        "secure delivery",
        "security",
        "sensitive material",
        "service desk and ticketing",
        "service related risk",
        "social media",
        "social media analytics",
        "software design",
        "software design principles",
        "software development",
        "solicitor management",
        "sort and distribute mail",
        "spreadsheets",
        "staff communication",
        "stakeholder engagement",
        "stakeholder management",
        "statistical data",
        "strategic awareness",
        "strategic direction",
        "strategic leadership",
        "succession planning",
        "supplier management",
        "supply chain management",
        "support line managers",
        "supporting financial governance",
        "surveillance systems",
        "sustainability",
        "system and software requirements",
        "system resilience",
        "systems design",
        "systems engineering",
        "task organisation",
        "tax technical learning",
        "teaching",
        "team collaboration",
        "team communication",
        "team delivery",
        "team development",
        "team mailbox management",
        "team management",
        "team matrix management",
        "team workload management",
        "teamwork",
        "technical communication",
        "technical design",
        "technical user stories",
        "technology adoption",
        "test development",
        "theory based evaluation",
        "time management",
        "tool migration",
        "trade policy",
        "training course delivery",
        "training delivery",
        "training workshops",
        "troubleshooting",
        "user centred design",
        "user feedback",
        "user research",
        "user researcher",
        "user story",
        "user technology",
        "user-led design",
        "vaccines",
        "verbal communication",
        "version control",
        "virtual learning",
        "virtual teams",
        "visualise outcomes",
        "visualising problems",
        "water management",
        "weapon and firearm handling",
        "web accessibility",
        "web content management",
        "web publishing",
        "web technology",
        "workforce planning",
        "working with external partners",
        "working with senior managers",
        "workshop facilitation",
        "writing",
        "writing briefing notes",
        "written and oral communication",
        "written and verbal communication",
        "written communication",
    ]
)


DDAT_SKILLS_TO_JOB_LOOKUP = {
    "Accessibility": ["Frontend developer"],
    "Agile and Lean practices": ["Delivery manager", "Programme delivery manager"],
    "Agile working": [
        "Business analyst",
        "Product manager",
        "Service owner",
        "Content strategist",
        "Graphic designer",
        "Interaction designer",
        "Service designer",
        "Technical writer",
    ],
    "Agile working (content design)": ["Content designer"],
    "Analysis": ["Security architect"],
    "Analysis and synthesis": ["Data analyst", "User researcher", "Data ethicist"],
    "Analysis and insight": ["Performance analyst"],
    "Applied knowledge of social sciences": ["Data ethicist"],
    "Applied maths, statistics and scientific practices": ["Data scientist"],
    "Asset and configuration management": [
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Application operations engineer",
    ],
    "Availability and capacity management": [
        "Change and release manager",
        "Command and control centre manager",
        "Infrastructure operations engineer",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
        "Development operations (DevOps) engineer",
        "Software developer",
        "Application operations engineer",
    ],
    "Business analysis": ["Business analyst"],
    "Business analysis (IT operations)": ["Business relationship manager", "IT service manager"],
    "Business process improvement": ["Business analyst"],
    "Business modelling": ["Business analyst"],
    "Business process testing": ["Business analyst"],
    "Change management": [
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
        "Application operations engineer",
    ],
    "Coding and scripting infrastructure": ["Infrastructure operations engineer", "Infrastructure engineer"],
    "Commercial management": ["Delivery manager", "Programme delivery manager"],
    "Commercial perspective": ["Enterprise architect"],
    "Communication": ["Data analyst"],
    "Communicating analysis and insight": ["Performance analyst"],
    "Communicating between the technical and non-technical": [
        "Graphic designer",
        "Technical architect",
        "Data ethicist",
        "Data engineer",
        "Data architect",
        "Programme delivery manager",
        "Interaction designer",
        "Delivery manager",
        "Enterprise architect",
        "Accessibility specialist",
    ],
    "Communicating data": ["Data architect"],
    "Communicating information": ["Frontend developer", "Service designer"],
    "Communication skills": ["Programme delivery manager", "Data ethicist"],
    "Communication skills (security architect)": ["Security architect"],
    "Community collaboration": [
        "Change and release manager",
        "Command and control centre manager",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
        "Programme delivery manager",
        "Frontend developer",
        "Graphic designer",
        "Interaction designer",
        "Service designer",
        "Enterprise architect",
    ],
    "Content concepts and prototyping": ["Content designer"],
    "Continual service improvement": [
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Application operations engineer",
    ],
    "Consultancy": ["Business analyst", "Accessibility specialist"],
    "Continuity management": [
        "Change and release manager",
        "Command and control centre manager",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
    ],
    "Customer service management": ["Service desk manager"],
    "Data analysis and synthesis": ["Data engineer", "Data architect"],
    "Data development process": ["Data engineer"],
    "Data engineering and manipulation": ["Data science"],
    "Data governance": ["Data architect"],
    "Data innovation": ["Data engineer", "Data architect"],
    "Data integration design": ["Data engineer"],
    "Data management": ["Data analyst"],
    "Data modelling": ["Data engineer", "Data architect"],
    "Data modelling, data cleansing and data enrichment": ["Data analyst"],
    "Data quality assurance, validation and linkage": ["Data analyst"],
    "Data science innovation": ["Data scientist"],
    "Data standards": ["Data architect"],
    "Data visualisation": ["Data analyst"],
    "DDaT perspective": ["Product manager", "Service owner", "Enterprise architect"],
    "Delivering business impact": ["Data scientist"],
    "Designing secure systems": ["Security architect"],
    "Development process optimisation": ["Software developer", "Development operations (DevOps) engineer"],
    "Developing data science capability": ["Data scientist"],
    "Digital perspective": ["Business analyst", "Graphic designer", "Interaction designer", "Service designer"],
    "Empathy and inclusivity": ["Dat ethicist"],
    "Enabling and informing risk-based decisions": ["Security architect"],
    "Enterprise and business architecture": ["Business analyst", "Enterprise architect"],
    "Ethics and privacy": ["Data ethicist", "Data science"],
    "Evidence- and context-based design": ["Graphic designer", "Interaction designer", "Service designer"],
    "Experience of working within constraints": ["Service designer"],
    "Facilitating decisions and risks": ["Service designer"],
    "Financial management": ["Delivery manager", "Programme delivery manager"],
    "Financial ownership": ["Product manager", "Service owner"],
    "Functional testing": ["Quality Assurance Testing (QAT) analyst", "Test engineer", "Test manager"],
    "Governance and assurance": [
        "Accessibility specialist",
        "Network architect",
        "Technical architect",
        "Enterprise architect",
    ],
    "Incident management": [
        "Application operations engineer",
        "Change and release manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
        "Command and control centre manager",
    ],
    "Inclusive research": ["User researcher"],
    "Information security": [
        "Development operations (DevOps) engineer",
        "Infrastructure engineer",
        "Software developer",
    ],
    "Innovation": ["Business analyst"],
    "IT and mathematics": ["Data analyst"],
    "IT infrastructure": ["Infrastructure engineer"],
    "IT infrastructure (network architect)": ["Network architect"],
    "Leadership and guidance": [
        "Accessibility specialist",
        "Frontend developer",
        "Graphic designer",
        "Interaction designer",
        "Service designer",
    ],
    "Life-cycle perspective": ["Delivery manager", "Product manager", "Programme delivery manager", "Service owner"],
    "Logical and creative thinking": ["Data analyst"],
    "Maintaining delivery momentum": ["Delivery manager", "Programme delivery manager"],
    "Making and guiding decisions": ["Technical architect", "Enterprise architect"],
    "Making a process work": ["Delivery manager", "Programme delivery manager"],
    "Managing decisions and risks": ["Data ethicist"],
    "Metadata management": ["Data engineer", "Data architect"],
    "Methods and tools": ["Business analyst"],
    "Modern standards approach": [
        "Development operations (DevOps) engineer",
        "Frontend developer",
        "Infrastructure engineer",
        "Software developer",
    ],
    "Non-functional testing": ["Quality Assurance Testing (QAT) analyst", "Test engineer", "Test manager"],
    "Operational management": ["Product manager", "Service owner"],
    "Ownership and initiative": [
        "Application operations engineer",
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Infrastructure engineer",
    ],
    "Performance measurement": ["Performance analyst"],
    "Planning": ["Delivery manager", "Programme delivery manager"],
    "Problem definition and shaping": ["Enterprise architect"],
    "Problem management": [
        "Application operations engineer",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
        "Data ethicist",
        "Service owner",
        "Product manager",
        "Infrastructure engineer",
        "Service desk management",
    ],
    "Problem resolution (data)": ["Data engineer", "Data architect"],
    "Product ownership": ["Product manager", "Service owner", "Data ethicist"],
    "Programming and build": ["Frontend developer"],
    "Programming and build (data engineering)": ["Data engineer"],
    "Programming and build (data science)": ["Data science"],
    "Programming and build (software engineering)": ["Development operations (DevOps) engineer", "Software developer"],
    "Project management": ["Data analyst"],
    "Prototyping": [
        "Development operations (DevOps) engineer",
        "Frontend developer",
        "Software developer",
        "Content strategist",
        "Graphic designer",
        "Interaction designer",
        "Service designer",
        "Technical writer",
    ],
    "Prototyping in code": ["Graphic designer", "Interaction designer", "Service designer"],
    "Relationship management": ["Business relationship manager", "IT service manager"],
    "Requirements definition and management": ["Business analyst"],
    "Research": ["User researcher"],
    "Research and innovation": ["Security architect"],
    "Service focus": [
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Application operations engineer",
        "Infrastructure engineer",
    ],
    "Service management": ["Application operations engineer"],
    "Service management framework knowledge": [
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service transition manager",
        "Service desk manager",
    ],
    "Service reporting": [
        "Business relationship manager",
        "End user computing engineer",
        "IT service manager",
        "Service desk manager",
    ],
    "Service support": ["Development operations (DevOps) engineer", "Software developer"],
    "Society and technology": ["User researcher"],
    "Security technology": ["Security architect"],
    "Stakeholder relationship management": [
        "Business analyst",
        "Content strategist",
        "Technical writer",
        "Data ethicist",
    ],
    "Stakeholder relationship management (content design)": ["Content designer"],
    "Statistical methods and data analysis": ["Data analyst"],
    "Strategiv design and business change": ["Enterprise architect"],
    "Strategic insight": ["User researcher"],
    "Strategic ownership": ["Product manager", "Service owner"],
    "Strategic thinking": [
        "Business relationship manager",
        "IT service manager",
        "Frontend developer",
        "Content strategist",
        "Graphic designer",
        "Interaction designer",
        "Service designer",
        "Technical writer",
    ],
    "Strategic thinking (content design)": ["Content designer"],
    "Strategic thinking (data architecture)": ["Data architect"],
    "Strategy": ["Technical architect"],
    "Systems analysis": ["Business analyst"],
    "Systems design": [
        "Frontend developer",
        "Infrastructure engineer",
        "Network architect",
        "Software developer",
        "Development operations (DevOps) engineer",
    ],
    "Systems integration": [
        "Frontend developer",
        "Infrastructure engineer",
        "Software developer",
        "Development operations (DevOps) engineer",
    ],
    "Systems integration (network architect)": ["Network architect"],
    "Team dynamics and collaboration": ["Delivery manager"],
    "Technical breadth": ["Quality Assurance Testing (QAT) analyst", "Test engineer", "Test manager"],
    "Technical specialism": [
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Application operations engineer",
    ],
    "Technical understanding": [
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Technical writer",
        "User researcher",
        "Application operations engineer",
        "Infrastructure engineer",
        "Performance analyst",
        "Accessibility specialist",
        "Data engineer",
        "Network architect",
    ],
    "Test analysis": ["Quality Assurance Testing (QAT) analyst", "Test engineer", "Test manager"],
    "Testing": [
        "Data engineer",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Application operations engineer",
        "Infrastructure engineer",
        "Accessibility specialist",
    ],
    "Testing (business analysis)": ["Business analyst"],
    "Tools and software": ["Graphic design"],
    "Troubleshooting and problem resolution": ["Infrastructure engineer", "Network architect"],
    "Turning business problems into data design": ["Data architect"],
    "Turning business problems into technical design": ["Technical architect"],
    "Understanding analysis across the product lifecycle": ["Performance analyst"],
    "Understanding product delivery": ["Data scientist"],
    "Understanding security implications of transformation": ["Security architect"],
    "Understanding the whole context": ["Technical architect"],
    "User experience analysis": ["Business analyst"],
    "User focus": [
        "Accessibility specialist",
        "Application operations engineer",
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Business analyst",
        "Product manager",
        "Service owner",
        "Frontend developer",
        "Software developer",
        "Content strategist",
        "Graphic designer",
        "Interaction designer",
        "Service designer",
        "Technical writer",
        "Development operations (DevOps) engineer",
    ],
    "User focus (content design)": ["Content designer"],
    "User-centred analysis": ["Performance analyst"],
    "User-centred and agile practices": ["User researcher"],
    "User-centred content design": ["Content designer", "Content strategist", "Technical writer"],
    "Verification and validation of data and analysis": ["Performance analyst"],
    "Web performance optimisation": ["Frontend developer"],
    "Working within constraints": [
        "Graphic designer",
        "Product manager",
        "Interaction designer",
        "Performance analyst",
    ],
}

DDAT_JOB_TO_SKILLS_LOOKUP = reverse_dict_lists(DDAT_SKILLS_TO_JOB_LOOKUP)
