from ellandi.registration.utils import reverse_dict_lists

INITIAL_SKILLS = set(
    [
        "Accessibility",
        "Agile and Lean practices",
        "Agile working",
        "Agile working (content design)",
        "Analysis",
        "Analysis and synthesis",
        "Analytical and problem-solving",
        "Asset and configuration management",
        "Availability and capacity management",
        "Bridging the gap between the technical and non-technical",
        "Business analysis",
        "Business analysis (IT operations)",
        "Business improvement process",
        "Business modelling",
        "Business process testing",
        "Change management",
        "Coding and scripting",
        "Commercial management",
        "Communicating analysis and insight",
        "Communicating information",
        "Communication skills",
        "Communication skills (data)",
        "Communication skills (security architect)",
        "Community collaboration",
        "Content concepts and prototyping",
        "Continual service improvement",
        "Continuity management",
        "Customer service management",
        "Cyber/security",
        "Data analysis and synthesis",
        "Data communication",
        "Data development process",
        "Data governance",
        "Data innovation",
        "Data integration design",
        "Data management",
        "Data modelling",
        "Data modelling, data cleansing and data enrichment",
        "Data standards",
        "Data visualisation",
        "DDaT perspective",
        "Design secure systems",
        "Digital perspective",
        "Enabling and informing risk-based decisions",
        "Enterprise and business architecture",
        "Evidence- and context-based design",
        "Experience of using tools and software",
        "Experience of working within constraints",
        "Facilitating decisions and risks",
        "Financial management",
        "Financial ownership",
        "Functional testing",
        "Governance",
        "Governance and assurance",
        "Incident management",
        "Inclusive research",
        "Information security",
        "Innovation",
        "IT infrastructure",
        "IT infrastructure (network architect)",
        "Leadership and guidance",
        "Life-cycle perspective",
        "Logical and creative thinking",
        "Maintaining delivery momentum",
        "Making and guiding decisions",
        "Making the process work",
        "Metadata management",
        "Methods and tools",
        "Modern standards approach",
        "Non-functional testing",
        "Operational management",
        "Ownership and initiative",
        "Performance measurement",
        "Planning",
        "Problem management",
        "Problem ownership",
        "Problem resolution (data)",
        "Problem solving",
        "Product ownership",
        "Programming and build",
        "Programming and build (data engineering)",
        "Programming and build (software engineering)",
        "Project management",
        "Prototyping",
        "Prototyping in code",
        "Proven IT and mathematical",
        "Quality assurance, validation and data linkage",
        "Relationship management",
        "Requirements definition and management",
        "Research and innovation",
        "Research skills",
        "Service focus",
        "Service Management Framework knowledge",
        "Service reporting",
        "Service support",
        "Society and technology",
        "Specific security technology and understanding",
        "Stakeholder relationship management",
        "Stakeholder relationship management (content design)",
        "Statistical methods and data analysis",
        "Strategic insight",
        "Strategic ownership",
        "Strategic thinking",
        "Strategic thinking (content design)",
        "Strategic thinking (data architecture)",
        "Strategy",
        "Systems design",
        "Systems integration",
        "Systems integration (network architect)",
        "Team dynamics and collaboration",
        "Technical breadth",
        "Technical specialism",
        "Technical understanding",
        "Technical understanding (data engineering)",
        "Technical understanding (infrastructure engineer)",
        "Technical understanding (network architect)",
        "Technical understanding (performance analyst)",
        "Test analysis",
        "Testing",
        "Testing (business analysis)",
        "Troubleshooting and problem resolution",
        "Turning business problems into data design",
        "Turning business problems into technical design",
        "Understanding analysys across the product lifecycle",
        "Understanding constraints (performance analyst)",
        "Understanding security implications of transformation",
        "Understanding the whole context",
        "Undertaking analysis and providing insight",
        "User focus",
        "User focus (content design)",
        "User-centred analysis",
        "User-centred and agile practices",
        "User-centred content design",
        "Verification and validation of data and analysis",
        "Web performance optimisation",
    ]
)


NLP_DERIVED_SKILLS = set(
    [
        "Absence management support",
        "Access permission scheme",
        "Account team member",
        "Acquiring data understanding customer",
        "Action plan",
        "Adapt writing",
        "Adaptable to problems",
        "Address risk",
        "Administrative support",
        "Administrative task utilising",
        "Advice minister senior official",
        "Advise senior official",
        "Agent tax adviser",
        "Agile delivery",
        "Agile development using continuous integration principle",
        "Agile practises",
        "Agile project management tools",
        "Agile project management",
        "Agreed maintenance task",
        "Alarm system",
        "Ambiguity making",
        "Analysing large datasets",
        "Analysing qualitative comment",
        "Analysis synthesis",
        "Analytical intelligence product",
        "Animal welfare",
        "Annual newsletter",
        "Application development",
        "Application penetration testing",
        "Application system",
        "Appraisal process",
        "Appreciation legal risk",
        "Apprentice solicitor",
        "Apprenticeship scheme",
        "Approachable management style",
        "Appropriate professional body",
        "Archiving system",
        "Arrange travel and accomodation",
        "Arranging appointment",
        "Articulated timeline",
        "Assessing certification artefact",
        "Associated budget",
        "Associated tracker",
        "Assurance processes",
        "Assurance reviews",
        "Assuring technology decision",
        "Attendance management",
        "Audit risk",
        "Audit support",
        "Auditor team member",
        "Automation configuration management tools",
        "Automation service",
        "Aviation tasking",
        "Awareness-atlassian pm tool-",
        "Awareness-modelling tool-draw",
        "Balancing quality and cost effectiveness",
        "Based access control",
        "Basic numeracy",
        "Basic weapon handling",
        "Behavioural change",
        "Behavioural insight informs key decision",
        "Behavioural science",
        "Bespoke data set",
        "Bespoke learning package",
        "Bespoke math support",
        "Big data",
        "Body informing",
        "Border policy",
        "Broad direction",
        "Budget contract management",
        "Budget forecasting",
        "Budget management",
        "Budget risk",
        "Build automated test",
        "Build collaborative relationship",
        "Build effective relationship",
        "Build long term strategic relationship",
        "Build relationship",
        "Build user centred practice",
        "Building capability",
        "Building effective partnership",
        "Building key",
        "Building partnership",
        "Building relationship rapidly",
        "Building trusting relationship",
        "Business architectures",
        "Business cases",
        "Business data",
        "Business needs",
        "Business performance",
        "Business planning",
        "Business value",
        "Calendar management",
        "Capability audit",
        "Capability building",
        "Capability development",
        "Capacity management",
        "Car park management",
        "Cardholder query",
        "Cascade vision",
        "Case handling challenge",
        "Case management system",
        "Case management",
        "Cash seizures",
        "Category management practice",
        "CCAB qualified accountant",
        "CCUS delivery capability",
        "Continuous delivery pipeline",
        "Centred design presentation",
        "Ceso team member",
        "Challenge pupil",
        "Challenging timeline",
        "Champion user research",
        "Championing continuous improvement",
        "Championing diversity",
        "Championing user centred design",
        "Change communication",
        "Change control management",
        "Change control mechanism",
        "Change management",
        "Change package",
        "Change request",
        "Changing focus",
        "Changing terrorism threat",
        "Chat function",
        "Cleaning",
        "Clear communication influencing negotiations",
        "Clear communication",
        "Climate change and energy policy",
        "Climate model",
        "Climate policy",
        "Clinical sample",
        "Close liaison",
        "Close team sharing",
        "Cloud based",
        "Cloud/open source technologies",
        "Co-ordinating behaviour change project",
        "Coach develop",
        "Coaching",
        "Coding languages (R, VBA, SQL, Python, AWS)",
        "Coding",
        "Collaborative relationship",
        "Collaborative working",
        "Command continuous improvement",
        "Commercial activities",
        "Commercial advice",
        "Commercial approach",
        "Commercial awareness",
        "Commercial capability",
        "Commercial contract",
        "Commercial financial audit",
        "Commercial judgement",
        "Commercial negotiation",
        "Commercial programme",
        "Commercial relationships",
        "Commercial risk",
        "Commercial supplier relationship",
        "Commitment continuing professional development",
        "Commitment providing customer service",
        "Common goal",
        "Communicate confidently",
        "Communicate effectively authoritatively",
        "Communicate effectively verbally",
        "Communicate effectively",
        "Communicate technical concept",
        "Communicate threat assessment",
        "Communicate uncertainty",
        "Communicating data analysis",
        "Communicating risk",
        "Communicating sensitive confidential information",
        "Communicating verbally",
        "Communication audit",
        "Communication data",
        "Communication order",
        "Communication presentation",
        "Communication product, brand guidelines",
        "Communication product",
        "Communication skills (oral and written)",
        "Communication staff",
        "Communication system",
        "Communication team agency",
        "Communication team",
        "Communication technology",
        "Communication",
        "Communications and engagement",
        "Communications evaluation",
        "Competing priority",
        "Complaint secretariat",
        "Completed accurately",
        "Complex fast paced",
        "Complex idea",
        "Complex information quickly",
        "Complex information verbally",
        "Compliance audit",
        "Compliance enforcement",
        "Compliance quality system",
        "Compliance standards",
        "Computer literacy",
        "Concurrently managing multiple project",
        "Conduct interviews",
        "Conduct training course",
        "Conduct-highest-core value",
        "Confidently analyse information",
        "Confidently handle potentially difficult",
        "Conflict fragile state",
        "Conflict resolution",
        "Conflicting priority",
        "Considerable financial commercial",
        "Consistent track record",
        "Consultancy project",
        "Content creation",
        "Content design specialist",
        "Continual learning",
        "Continually review",
        "Continued professional development",
        "Continuous capability improvement",
        "Continuous delivery",
        "Continuous improvement",
        "Continuous learning development",
        "Continuous personal",
        "Continuous professional development",
        "Continuously improve process",
        "Contract documentation",
        "Contract management",
        "Contract procurement",
        "Contract supervision delivery",
        "Contract supplier",
        "Contracted supply chain partnership",
        "Coordinate key project meeting",
        "Corporate process",
        "Correct implementation",
        "Cost estimating",
        "Cost management",
        "Cost modelling",
        "Cost reporting tool",
        "Counterparty relationship",
        "Courier logistics market",
        "Courts and tribunals",
        "Create great agile",
        "Creating resilient landscape",
        "Creating video content",
        "Creating virtual team",
        "Creative communication campaigns",
        "Creative industry",
        "Creative problem solving",
        "Creative solution",
        "Criminal case management",
        "Criminal justice",
        "Crisis management",
        "Cross team relationship",
        "Cross-Whitehall working",
        "Cross-team working",
        "Cryptographic item",
        "Customer expectation",
        "Customer guidance",
        "Customer journey",
        "Customer liaison",
        "Customer stakeholder management",
        "Customer support",
        "Customer/stakeholder relations",
        "Cyber risk",
        "Dashboards",
        "Data analysis",
        "Data backup and recovery",
        "Data engineering management",
        "Data engineering",
        "Data ethics",
        "Data extraction",
        "Data governance",
        "Data information",
        "Data informed decision making",
        "Data insight",
        "Data literacy and communication",
        "Data management",
        "Data modelling",
        "Data protection compliance",
        "Data quality assurance",
        "Data science management",
        "Data sharing agreement",
        "Data source",
        "Data standards",
        "Data storage",
        "Data strategy",
        "Data warehouse",
        "Database management",
        "Date record",
        "Day budget management",
        "Day interaction",
        "Day supervision",
        "Decision maker",
        "Decision making",
        "Defence policy",
        "Define technical standards",
        "Defines test condition",
        "Defining professional standards",
        "Deliberate search",
        "Deliver accurate-requested",
        "Deliver cultural change",
        "Deliver induction training",
        "Deliver organisational priority",
        "Deliver quality product",
        "Deliver shared",
        "Deliver supporting oral",
        "Deliver team output",
        "Deliver training presentation",
        "Deliverable communication advice",
        "Delivering behavioural intervention",
        "Delivering presentation",
        "Delivering technology change",
        "Delivery risk",
        "Demanding fast paced",
        "Demanding timescales",
        "Demonstrable quality outcome",
        "Demonstrable relationship management",
        "Departmental collaboration",
        "Dependency management",
        "Depth configuration",
        "Deputy project manager",
        "Design deliver",
        "Design governance",
        "Design related degree",
        "Designing programme",
        "Designing service",
        "Determine strategic vision",
        "Develop career",
        "Develop contract documentation",
        "Develop customer relationships",
        "Develop data solutions",
        "Develop peer networks",
        "Develop programme plan",
        "Develop system-save life",
        "Develop team members",
        "Develop technical standards",
        "Develop understanding",
        "Developing business case",
        "Developing business intelligence ",
        "Developing data science capability",
        "Developing digital product",
        "Developing key performance indicator",
        "Developing reporting",
        "Developing strategy",
        "Developing team capability",
        "Diary management",
        "Diary priority",
        "Digital context",
        "Digital forensics",
        "Digital literacy",
        "Digital telephony",
        "Digital transformation",
        "Diplomatic negotiation",
        "Distribute mail",
        "Document control",
        "Document user specifications",
        "Documentation management",
        "Drafting legislation",
        "Drafting maritime ministerial",
        "Drafting papers",
        "Draw sound",
        "Driven microservice architecture",
        "Driving",
        "Economic growth policy",
        "Economics",
        "Editing proofreading",
        "Editing",
        "Education policy",
        "Effective adoption intervention",
        "Effective communication-planning-delivery-",
        "Effective customer service",
        "Effective decision making problem",
        "Effective engagement",
        "Effective governance",
        "Effective inbox management",
        "Effective personal delivery",
        "Effective problem solving",
        "Effective working relationship",
        "Effectively prioritise",
        "Efficiency saving",
        "Electronic warfare",
        "Email query accurately",
        "Embedding equality legislation",
        "Embedding financial control",
        "Embedding robust",
        "Emergency response experience",
        "Emerging cyber threat",
        "Emerging technology",
        "Employee engagement",
        "Employee relation",
        "Employment law",
        "Employment legislation",
        "Empower team member",
        "Empowered culture",
        "Energetic management approach",
        "Energy carbon",
        "Energy policy and management",
        "Engagement strategy",
        "Engagement-manage-process-",
        "Engineering offshore",
        "Enjoy problem solving",
        "Enjoys solving problem",
        "Enterprise architecture",
        "Environmental economics",
        "Environmental policy",
        "Environmental scheme policy",
        "Epidemiological skills",
        "Equivalent project management software",
        "Establish professional relationship",
        "Establishes problem fix",
        "Ethical standards",
        "ETL design pipeline",
        "ETL scripts",
        "Evaluate learning intervention",
        "Event planning",
        "Evidence andknowledge",
        "Evidence based design",
        "Evidence based policy development",
        "Evidence based recommendation",
        "Evidence based",
        "Evidence creative",
        "Evidence data",
        "Evidential report",
        "Existing data flow",
        "Existing methodology",
        "Experience in user feedback",
        "Experience of HR",
        "Explain technology feature",
        "Explosive safety",
        "Export file doc",
        "Express judgement precisely",
        "External partner, collaboration-building",
        "External partner",
        "External relationship",
        "External stakeholder",
        "External supplier consultancy",
        "Extra resilience",
        "Facilitate learning conversation",
        "Facilitate request management",
        "Facilitate risk management",
        "Facilitate workshop training",
        "Facilitate workshop",
        "Facilitating agile ceremony",
        "Facility management supplier",
        "Fact finding",
        "Family policy",
        "Fast changing moving",
        "Fast paced programme",
        "Fast paced project",
        "Fast paced working",
        "Feedback customer",
        "File record",
        "Finance banking",
        "Finance commercial",
        "Finance functions",
        "Finance",
        "Financial analysis",
        "Financial contract management",
        "Financial control",
        "Financial controls",
        "Financial forecasting",
        "Financial information",
        "Financial management",
        "Financial modelling",
        "Financial planning",
        "Financial procurement",
        "Financial reporting",
        "Financial risk",
        "Fire diary",
        "Fire service",
        "Fiscal forecast",
        "Fishery research",
        "Flexible collaborative approach",
        "Flexible team member",
        "Flow team",
        "Follow protocol",
        "Food safety policy",
        "Formal performance management",
        "Formal qualification",
        "Formal questions",
        "Formal risk management qualification",
        "Forward planning",
        "Foster innovation",
        "Fraud policy",
        "Fuel card",
        "Future demand management",
        "Future fiscal event",
        "Future system",
        "GDPR",
        "Generating documentation",
        "Geographically dispersed team",
        "Geospatial data APIs",
        "Governance audit",
        "Government accounting",
        "Government context",
        "Government corporate governance",
        "Government digital",
        "Government housing",
        "Government meeting",
        "Graphic design",
        "Guidance colleague",
        "Guiding leader",
        "Habitat management",
        "Handle pressure",
        "Handling information request",
        "Health data",
        "Health safety policy",
        "Heavy plant machinery",
        "Heritage sector",
        "High ambiguity",
        "High level autonomy",
        "High profile",
        "High quality",
        "High standard written communication",
        "Highlighting deadline",
        "Highly numerate",
        "Highly organised",
        "HMRC strategic direction",
        "Hoc support",
        "Hoc task",
        "Horizon scanning intelligence",
        "Housekeeping duty",
        "Housing stock",
        "HR policy",
        "Hub duty assigned",
        "Idea quickly",
        "Identified risk",
        "Identify errors/ risks",
        "Identify key information",
        "Identify monitor project risk",
        "Identify obstacle",
        "Identify project dependency",
        "Identify project risk",
        "Identify simple pattern",
        "Immigration policy",
        "Immunisation update",
        "Impact evaluation",
        "Impactful analysis",
        "Implement style guidance",
        "Implementing change",
        "Implementing solution",
        "Implementing strategy",
        "Import export",
        "Include proactive PR",
        "Inclusive service pattern",
        "Inclusive service",
        "Inclusive workplace",
        "Income generation",
        "Increase engagement",
        "Industry recognised data modelling pattern",
        "Influencing senior official",
        "Inform content decision",
        "Informal assessment",
        "Information governance",
        "Information inform",
        "Information management",
        "Innovative idea",
        "Intelligence flow",
        "Intelligence report",
        "Intelligent customer",
        "Interaction design inside",
        "Internal communication channel",
        "International coordination",
        "International negotiation",
        "International politics",
        "Internet banking payment",
        "Interpersonal collaborative",
        "Interpersonal communication",
        "Interpersonal relationship",
        "Interpret environmental",
        "Interpreting data",
        "Interpreting financial information",
        "Interpreting information",
        "Intranet management",
        "Investment policy",
        "Invoicing",
        "Issue resolution",
        "IT skills",
        "Justice system",
        "Keen eye",
        "Keen interest",
        "Key business stakeholder",
        "Key change management",
        "Key data artefact",
        "Key evidence gap",
        "Key external stakeholder relationship",
        "Labour market",
        "Language stakeholder engagement",
        "Language teaching material",
        "Large organisation",
        "Law enforcement ",
        "Lead small medium project",
        "Leadership coaching",
        "Leadership evidence",
        "Leadership track record",
        "Leadership",
        "Leading change",
        "Leading investigations",
        "Leading research project",
        "Leading teams",
        "Learning development budget",
        "Ledger reconciliation",
        "Legal adviser",
        "Legal compliance policy",
        "Legal risk management",
        "Legal risk",
        "Legal training",
        "Legislation negotiation",
        "Legislative change",
        "Legislative complianced",
        "Level documentation",
        "Level headed",
        "Line management",
        "Line task management",
        "Link different data set",
        "Linked recommendation verbally",
        "Litigation and tax appeals",
        "Livestock management",
        "Loading unloading",
        "Local policy",
        "Location arrangement",
        "Machine learning",
        "Machine partnering",
        "Maintain audit trail",
        "Maintain communication",
        "Maintain currency",
        "Maintaing distribution lists",
        "Maintaining accurate financial record",
        "Maintaining appointment",
        "Maintaining effective relationship",
        "Maintaining office machinery",
        "Maintaining professionalism",
        "Maintaining relationships with journalists",
        "Maintaining safety standards",
        "Maintaining schedule",
        "Make sound judgement",
        "Making complex language simple",
        "Making judgement calls",
        "Making marine nature conservation byelaws",
        "Making presentation",
        "Manage budgets",
        "Manage business relationships",
        "Manage customer relationships",
        "Manage issues and risks",
        "Manage ministerial correspondence",
        "Manage performance confidently",
        "Manage procurement",
        "Manage social media",
        "Manage speechwriting team workload",
        "Manage time priority",
        "Manage time",
        "Manage update",
        "Management assurance check",
        "Management contractor",
        "Management control",
        "Management information",
        "Management system software",
        "Manager resourcing plan",
        "Manages effective transition",
        "Managing accomodation requirements",
        "Managing ambiguity",
        "Managing briefing requests",
        "Managing consulation responses",
        "Managing dashboards",
        "Managing data quality",
        "Managing examinations",
        "Managing external research contract",
        "Managing forecasting resources",
        "Managing litigation",
        "Managing personal data",
        "Managing project",
        "Managing risk",
        "Managing sickness and absence",
        "Managing support supplier",
        "Managing telephone enquiries",
        "Manual driving licence",
        "Marine ecology",
        "Market research",
        "Mathematical model",
        "Matrix delivery",
        "Meaningful report",
        "Mechanical electrical",
        "Mechanism contract management",
        "Medical product",
        "Medicinal product",
        "Meet customer demand",
        "Meet deadline",
        "Meet strict deadliness",
        "Meet user needs",
        "Meeting coordination",
        "Meeting event",
        "Meeting minutes",
        "Meeting room diary",
        "Mental health policy",
        "Mentoring",
        "Migrating solutions",
        "Military policy",
        "Minimal supervision",
        "Ministerial briefing",
        "Ministerial correspondence",
        "Ministerial direction",
        "Ministerial meeting",
        "Ministerial portfolio",
        "Ministerial private office",
        "Mitigate reputational risk",
        "Mixed grade",
        "Mobile device support",
        "Mobile software design",
        "Mobile telephone technology",
        "Modelling and simulation",
        "Modern coding language",
        "Money laundering",
        "Monitor insurance policy",
        "Monitor programme",
        "Monitor team mailbox",
        "Monitoring compliance",
        "Monitoring contract performance practitioner",
        "Monitoring contract supplier performance",
        "Monitoring inboxes",
        "Monitoring intelligence feeds",
        "Monitoring risk",
        "Monthly management account",
        "Mouth disease disposal",
        "Multi-disciplinary team management",
        "Multidisciplinary team",
        "Multiple project task",
        "Multiple project",
        "Multiple task",
        "Natural intellectual curiosity",
        "Navigate difficult conversations",
        "Negotiating grant agreement",
        "Negotiation",
        "Networking architecture",
        "Networking events",
        "Nuclear safety",
        "Offender management",
        "Offending behaviour programme",
        "Office filing system",
        "Office team",
        "Oil industry",
        "Oil spill",
        "Open source",
        "Operational data list",
        "Operational system support",
        "Operational team",
        "Oral communication interpersonal",
        "Oral communication",
        "Oral health",
        "Oral presentations",
        "Oral written communication",
        "Oral written drafting",
        "Ordinate engagement",
        "Organisational change",
        "Organisational management",
        "Organisational strategy",
        "Organisational task",
        "Organised crime",
        "Organising conferences",
        "Orientated development language",
        "Outdoor leisure",
        "Outgoing mail dispatch",
        "Outsourced suppliers",
        "Overseas investigation",
        "Overseas law enforcement partner",
        "Oversee timely",
        "Ownership delivering",
        "Paced agile",
        "Paced policy",
        "Parliamentary correspondence",
        "Parliamentary government liaison",
        "Parliamentary process",
        "Partner meeting",
        "Party delivery",
        "Party supplier",
        "Password reset request",
        "Pay governance",
        "Peer coaching",
        "Peer review",
        "Pensions policy",
        "Performance data",
        "Performance insight reporting",
        "Performance metric",
        "Performance monitoring alerting",
        "Period change",
        "Personal accountability",
        "Personal credibility",
        "Personal integrity honesty",
        "Personal resilience",
        "Persuasive communicator",
        "Pest control",
        "Pesticide user",
        "Photo editing software",
        "Photocopying faxing",
        "Place stationary order",
        "Planning and scheduling",
        "Planning communication",
        "Planning meeting",
        "Planning multiple workstreams",
        "Planning",
        "Plant pest",
        "Policy change",
        "Policy compliance framework",
        "Policy development",
        "Policy legislative change",
        "Policy workstreams",
        "Portfolio reporting",
        "Portfolio risk",
        "Positive approach",
        "Positive attitude",
        "Positive team culture",
        "PQs and FOIs",
        "Pragmatic approach solving problem",
        "Prepare case files",
        "Preparing tribunal hearings",
        "Presentation coaching",
        "Presentation writing",
        "Presenting at events",
        "Presenting data",
        "Presenting research",
        "Presenting training session",
        "Preventative measure",
        "Printing",
        "Prioritise case",
        "Prioritise effectively",
        "Prioritise workload",
        "Prioritised backlog",
        "Prioritising resource",
        "Prioritising task",
        "Private office team",
        "Proactive approach",
        "Proactive team worker",
        "Proactively share",
        "Problem management",
        "Problem solving",
        "Process mapping",
        "Process perform optimally",
        "Procurement",
        "Produce guidance documents",
        "Producing briefing note",
        "Producing investment business case",
        "Producing witness statement",
        "Product life cycle",
        "Product management",
        "Product vision",
        "Productivity plan",
        "Productivity spreadsheet",
        "Professional accreditation",
        "Professional competence framework",
        "Professional development and community",
        "Professional development",
        "Professional programme project management",
        "Proficient in Microsoft Office Suite",
        "Profile programme",
        "Profile project, moving-great",
        "Profile project",
        "Programme benefit",
        "Programme change control",
        "Programme content",
        "Programme context",
        "Programme coordination",
        "Programme delivery",
        "Programme dependency",
        "Programme learning",
        "Programme mailbox",
        "Programme management delivery",
        "Programme management product",
        "Programme management",
        "Programme plan",
        "Programme project overseas",
        "Programme risk",
        "Programmed workforce efficiency",
        "Programming language",
        "Project assurance",
        "Project communication",
        "Project control reporting",
        "Project delivery process",
        "Project delivery profession",
        "Project forward",
        "Project governance",
        "Project lead",
        "Project management language",
        "Project management professional",
        "Project management technique",
        "Project management tool",
        "Project management",
        "Project meet",
        "Project performance reporting",
        "Project plan",
        "Project programme",
        "Project risk management",
        "Project team resource",
        "Project team",
        "Project tight deadline",
        "Property portfolio",
        "Proposing solution",
        "Prototyping",
        "Prototyping",
        "Provide administrative support",
        "Provide assurance",
        "Provide clinical",
        "Provide cross cutting",
        "Provide diary management",
        "Provide governance assurance",
        "Provide language reach",
        "Provide line management",
        "Provide problem fix",
        "Provide prompt accurate",
        "Provide regular progress update",
        "Provide secretariat",
        "Provide subject matter expertise",
        "Provide workflow management",
        "Providing administrative",
        "Providing advice",
        "Providing coherence",
        "Providing constructive challenge",
        "Providing input",
        "Providing oral briefing",
        "Providing regular feedback",
        "Providing regular progress update",
        "Providing secretariat support meeting",
        "Providing task management",
        "Providing technical input",
        "Public expenditure framework",
        "Public relations",
        "Public sector procurement legislation",
        "Public speaking and presentations",
        "Publishing web",
        "Purchase ordering",
        "Python coding",
        "Qualitative analysis",
        "Qualitative evidence",
        "Quality assurance",
        "Quality service delivering",
        "Quality written communication",
        "Query languages",
        "Quick learner",
        "Quickly assimilating information",
        "R programming languages",
        "Radiation protection",
        "Raise awareness-related subject-",
        "Raise team profile",
        "Reactive communication",
        "Reactive team",
        "Reactive workload",
        "Real passion",
        "Receipt dispatch",
        "Receipting and processing invoices",
        "Recognised project management qualification",
        "Recommend improvement",
        "Recordkeeping",
        "Recruitment",
        "Regular stock check",
        "Regulatory enforcement",
        "Regulatory framework",
        "Regulatory product",
        "Regulatory scientific",
        "Rehearsal disaster recovery",
        "Reinforce team commitment",
        "Related project programme",
        "Relational databases",
        "Relationship building",
        "Relationship internal external stakeholder",
        "Relationship key stakeholder",
        "Relationship management",
        "Remains alert emerging",
        "Remove blocker",
        "Report preparation",
        "Report writing",
        "Reporting communication",
        "Reporting governance",
        "Reporting risk",
        "Reporting safety",
        "Representing data truthfully",
        "Research data",
        "Research grants and funding",
        "Resilience stability",
        "Resolve dependency",
        "Resource achieve",
        "Resource deliver",
        "Resource management tools",
        "Respectful relationship internally",
        "Respond flexibly",
        "RESTful APIs",
        "Reverse engineer data model",
        "Revising inspection protocol",
        "Reward performance",
        "Reward policy",
        "Risk assessment documentation",
        "Risk assessment",
        "Risk context",
        "Risk dependency",
        "Risk governance framework",
        "Risk identification",
        "Risk management",
        "Risk marine",
        "Room and desk booking systems",
        "Room booking",
        "Running workshop",
        "Safe laboratory working practice",
        "Safeguarding children",
        "Schedule manage project resource",
        "Scheme payment",
        "Scientific degree",
        "Scientific method",
        "Scientific writing",
        "Scripting data management",
        "Search engine optimisation",
        "Search warrants",
        "Season ticket loan childcare voucher",
        "Secretarial support",
        "Secure data",
        "Secure delivery",
        "Security breach",
        "Security clearance",
        "Security governance",
        "Seek data sourcing",
        "Senior manager",
        "Senior product manager",
        "Sensitive data management",
        "Sensor design",
        "Service build",
        "Service desk",
        "Service design",
        "Service related risk",
        "Set direction",
        "Shape engineering",
        "Shared goal",
        "Sharing information",
        "Ship submarine",
        "Similar level",
        "Simple communication",
        "Skilled delivery team",
        "Social media analytics",
        "Social media",
        "Social research",
        "Software asset",
        "Software component",
        "Software design pattern",
        "Software design principles",
        "Software design",
        "Software development",
        "Software licence",
        "Solving customer",
        "Sophisticated change",
        "Sort and distribute mail",
        "Sound evidence base",
        "Sound judgement",
        "Sound programme",
        "Source control",
        "Sovereign debt",
        "Space technology",
        "Specialist extremism assessment",
        "Specialist microbiology theory",
        "Specialist molecular testing",
        "Spreadsheets",
        "Staff engagement",
        "Staff forecasting",
        "Staff overseas",
        "Staffing and HR data",
        "Stakeholder communication meeting",
        "Stakeholder management, stakeholder-internal",
        "Stakeholder management",
        "Stakeholder manages relationship effectively",
        "Stakeholder relationship, internal-external",
        "Stakeholder relationship",
        "Standard format",
        "Stated budget",
        "Stationery account",
        "Stationery stock",
        "Stationery supply",
        "Statistical analysis software",
        "Statistical analysis",
        "Statistical data",
        "Statistical sampling",
        "Statistical trends",
        "Statutory requirements",
        "Stores and inventory",
        "Strategic direction",
        "Strategic priority",
        "Strategic thinking",
        "Streaming system",
        "Succession planning",
        "Supplier customer networks",
        "Supplier management",
        "Supplier partner stakeholder",
        "Supplier relationship manager",
        "Supply chain",
        "Support analysis",
        "Support effective communication",
        "Support effective governance",
        "Support initiative",
        "Support line managers",
        "Support programme development",
        "Support project assurance",
        "Support response-humanitarian emergency",
        "Support sustainability",
        "Support-hr routine-project-",
        "Supporting financial governance",
        "Supporting governance",
        "Supporting programme governance",
        "Supporting project programme",
        "Supporting team communication",
        "Surveillance systems",
        "Survey data",
        "Sustain effective working relationship",
        "Sustain stakeholder relationship",
        "Sustainable forestry",
        "System and software requirements",
        "System change",
        "System performance",
        "Tackling modern slavery",
        "Tactical strategic",
        "Tailoring communication style",
        "Talent management and development",
        "Tax technical learning",
        "Teaching staff",
        "Team colleague, motivating-small",
        "Team colleague",
        "Team communication",
        "Team makeup",
        "Team management development",
        "Team matrix management",
        "Team member, leaders-managers",
        "Team member, motivating-small",
        "Team member",
        "Team player, networking-personal",
        "Team player",
        "Team priority",
        "Team process",
        "Team sharing",
        "Team spirit",
        "Team visualise outcome",
        "Team worker",
        "Technical advice",
        "Technical communication",
        "Technical design",
        "Technical drawing",
        "Technical expertise",
        "Technical management",
        "Technical system",
        "Technical user stories",
        "Technology adoption",
        "Telephone manner",
        "Tender documentation",
        "Term course planning",
        "Term financial plan",
        "Term priority",
        "Term project",
        "Testing practice",
        "Testing prototyping",
        "Testing techniques",
        "Thematic team",
        "Theory based evaluation approach",
        "Tight deadline pressure",
        "Time cost",
        "Time management task prioritisation",
        "Time management, attendance-arrangements",
        "Time management, resource-time",
        "Time management",
        "Time management",
        "Timely fashion",
        "Tool migration",
        "Track and manage incidents",
        "Track interdependency",
        "Track record delivering",
        "Track record",
        "Trade policy expertise",
        "Trade policy",
        "Training coaching",
        "Translate architectural design",
        "Translates logical design",
        "Travel overnight stay",
        "Travel overseas",
        "Troubleshooting",
        "Trusted relationship",
        "TUPE transfers",
        "Typing",
        "Unblock issue",
        "Underlying capability",
        "Understand project management",
        "Understand user story",
        "Understanding analysis output",
        "Understanding customer",
        "Understanding financial",
        "Understanding of policing landscape",
        "Understands organisational",
        "Unify design language",
        "Unswerving accuracy",
        "User acceptance testing",
        "User centred content design",
        "User centred content",
        "User centred service design practice",
        "User feedback",
        "User journey flow",
        "User product",
        "User research data",
        "User research method",
        "User research specialist",
        "User research",
        "User researcher, staff-coach",
        "User researcher",
        "User review",
        "User story",
        "User technology",
        "User-led design",
        "Utilising management information",
        "Vaccine preventable disease",
        "Validating dynamic prototype",
        "Valuations",
        "Value different",
        "Value money",
        "Varied workload",
        "Vat batch",
        "Verbal advice",
        "Verbal communication",
        "Verbal instruction",
        "Verbal written communication",
        "Verbal written numerical",
        "Version control",
        "Video conferencing",
        "Video filming and editing",
        "Virtual desktop",
        "Virtual learning",
        "Visitor engagement",
        "Visualise design problem",
        "Visualise information",
        "Vocational qualification",
        "Vulnerability analysis",
        "Waste management",
        "Water management",
        "Web accessibility",
        "Web applications",
        "Web content management",
        "Web security",
        "Web technology",
        "Whitehall networks",
        "Witness management",
        "Word security matter",
        "Workforce planning",
        "Workload management",
        "Workload meet tight deadline",
        "Wpm vision",
        "Wps customer",
        "Writing business case",
        "Writing engaging content",
        "Writing project",
        "Writing sops",
        "Written communication",
    ]
)


DDAT_SKILLS_TO_JOB_LOOKUP = {
    "Accessibility": ["Frontend developer"],
    "Agile and Lean practices": ["Delivery manager", "Programme delivery manager"],
    "Agile working": [
        "Business analyst",
        "Product manager",
        "Service owner",
        "Content strategist",
        "Graphic designer",
        "Interaction designer",
        "Service designer",
        "Technical writer",
    ],
    "Agile working (content design)": ["Content designer"],
    "Analysis": ["Security architect"],
    "Analysis and synthesis": ["User researcher", "Data ethicist"],
    "Analytical and problem-solving": ["Data analyst"],
    "Applied knowledge of social sciences": ["Data ethicist"],
    "Applied maths, statistics and scientific practices": ["Data scientist"],
    "Asset and configuration management": [
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Application operations engineer"
    ],
    "Availability and capacity management": [
        "Change and release manager",
        "Command and control centre manager",
        "Infrastructure operations engineer",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
        "Development operations (DevOps) engineer",
        "Software developer",
        "Application operations engineer"
    ],
      "Business analysis": ["Business analyst"],
    "Business analysis (IT operations)": ["Business relationship manager", "IT service manager"],
    "Business improvement process": ["Business analyst"],
    "Business modelling": ["Business analyst"],
    "Business process testing": ["Business analyst"],
    "Change management": [
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
        "Application operations engineer"
    ],
    "Coding and scripting infrastructure": ["Infrastructure operations engineer", "Infrastructure engineer"],
    "Commercial management": ["Delivery manager", "Programme delivery manager"],
    "Communicating analysis and insight": ["Performance analyst"],
    "Communicating between the technical and non-technical": ["Graphic designer", "Technical architect", "Data ethicist", "Data engineer", "Data architect"],
    "Communicating data": ["Data architect"],
    "Communicating information": ["Frontend developer", "Interaction designer", "Service designer"],
    "Communication skills": ["Data analyst", "Delivery manager", "Programme delivery manager", "Data ethicist"],
    "Communication skills (security architect)": ["Security architect"],
    "Community collaboration": [
        "Change and release manager",
        "Command and control centre manager",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
        "Programme delivery manager",
        "Frontend developer",
        "Graphic designer",
        "Interaction designer",
        "Service designer",
    ],
    "Content concepts and prototyping": ["Content designer"],
    "Continual service improvement": [
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Application operations engineer"
    ],
    "Continuity management": [
        "Change and release manager",
        "Command and control centre manager",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
    ],
    "Customer service management": ["Service desk manager"],
    "Data analysis and synthesis": ["Data engineer", "Data architect"],
    "Data development process": ["Data engineer"],
    "Data engineering and manipulation": ["Data science"],
    "Data governance": ["Data architect"],
    "Data innovation": ["Data engineer", "Data architect"],
    "Data integration design": ["Data engineer"],
    "Data management": ["Data analyst"],
    "Data modelling": ["Data engineer", "Data architect"],
    "Data modelling, data cleansing and data enrichment": ["Data analyst"],
    "Data science innovation": ["Data scientist"],
    "Data standards": ["Data architect"],
    "Data visualisation": ["Data analyst"],
    "DDaT perspective": ["Product manager", "Service owner"],
    "Delivering business impact": ["Data scientist"],
    "Designing secure systems": ["Security architect"],
    "Development process optimisation": ["Software developer", "Development operations (DevOps) engineer"],
    "Developing data science capability": ["Data scientist"],
    "Digital perspective": ["Business analyst", "Graphic designer", "Interaction designer", "Service designer"],
    "Empathy and inclusivity": ["Dat ethicist"],
    "Enabling and informing risk-based decisions": ["Security architect"],
    "Enterprise and business architecture": ["Business analyst"],
    "Ethics and privacy": ["Data ethicist", "Data science"],
    "Evidence- and context-based design": ["Graphic designer", "Interaction designer", "Service designer"],
    "Experience of working within constraints": ["Interaction designer", "Service designer"],
    "Facilitating decisions and risks": ["Service designer"],
    "Financial management": ["Delivery manager", "Programme delivery manager"],
    "Financial ownership": ["Product manager", "Service owner"],
    "Functional testing": ["Quality Assurance Testing (QAT) analyst", "Test engineer", "Test manager"],
    "Governance and assurance": ["Network architect", "Technical architect"],
    "Incident management": [
        "Application operations engineer",
        "Change and release manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
        "Command and control centre manager",
    ],
    "Inclusive research": ["User researcher"],
    "Information security": [
        "Development operations (DevOps) engineer",
        "Infrastructure engineer",
        "Software developer",
    ],
    "Innovation": ["Business analyst"],
    "IT infrastructure": ["Infrastructure engineer"],
    "IT infrastructure (network architect)": ["Network architect"],
    "Leadership and guidance": ["Frontend developer", "Graphic designer", "Interaction designer", "Service designer"],
    "Life-cycle perspective": ["Delivery manager", "Product manager", "Programme delivery manager", "Service owner"],
    "Logical and creative thinking": ["Data analyst"],
    "Maintaining delivery momentum": ["Delivery manager", "Programme delivery manager"],
    "Making and guiding decisions": ["Technical architect"],
    "Making the process work": ["Delivery manager", "Programme delivery manager"],
    "Managing decisions and risks": ["Data ethicist"],
    "Metadata management": ["Data engineer", "Data architect"],
    "Methods and tools": ["Business analyst"],
    "Modern standards approach": [
        "Development operations (DevOps) engineer",
        "Frontend developer",
        "Infrastructure engineer",
        "Software developer",
    ],
    "Non-functional testing": ["Quality Assurance Testing (QAT) analyst", "Test engineer", "Test manager"],
    "Operational management": ["Product manager", "Service owner"],
    "Ownership and initiative": [
        "Application operations engineer",
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Infrastructure engineer",
    ],
    "Performance measurement": ["Performance analyst"],
    "Planning": ["Delivery manager", "Programme delivery manager"],
    "Problem management": [
        "Application operations engineer",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "Problem manager",
        "Service transition manager",
        "Data ethicist",
        "Service owner",
        "Product manager",
        "Infrastructure engineer"
    ],
    "Problem resolution (data)": ["Data engineer", "Data architect"],
    "Product ownership": ["Product manager", "Service owner", "Data ethicist"],
    "Programming and build": ["Frontend developer"],
    "Programming and build (data engineering)": ["Data engineer"],
    "Programming and build (data science)": ["Data science"],
    "Programming and build (software engineering)": ["Development operations (DevOps) engineer", "Software developer"],
    "Project management": ["Data analyst"],
    "Prototyping": [
        "Development operations (DevOps) engineer",
        "Frontend developer",
        "Software developer",
        "Content strategist",
        "Graphic designer",
        "Interaction designer",
        "Service designer",
        "Technical writer",
    ],
    "Prototyping in code": ["Graphic designer", "Interaction designer", "Service designer"],
    "Proven IT and mathematical": ["Data analyst"],
    "Quality assurance, validation and data linkage": ["Data analyst"],
    "Relationship management": ["Business relationship manager", "IT service manager"],
    "Requirements definition and management": ["Business analyst"],
    "Research": ["User researcher"],
    "Research and innovation": ["Security architect"],
    "Service focus": [
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Application operations engineer",
        "Infrastructure engineer"
    ],
    "Service management": ["Application operations engineer"],
    "Service Management Framework knowledge": [
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service transition manager",
    ],
    "Service reporting": [
        "Business relationship manager",
        "End user computing engineer",
        "IT service manager",
        "Service desk manager",
    ],
    "Service support": ["Development operations (DevOps) engineer", "Software developer"],
    "Society and technology": ["User researcher"],
    "Security technology": ["Security architect"],
    "Stakeholder relationship management": ["Business analyst", "Content strategist", "Technical writer", "Data ethicist"],
    "Stakeholder relationship management (content design)": ["Content designer"],
    "Strategic insight": ["User researcher"],
    "Strategic ownership": ["Product manager", "Service owner"],
    "Strategic thinking": [
        "Business relationship manager",
        "IT service manager",
        "Frontend developer",
        "Content strategist",
        "Graphic designer",
        "Interaction designer",
        "Service designer",
        "Technical writer",
    ],
    "Strategic thinking (content design)": ["Content designer"],
    "Strategic thinking (data architecture)": ["Data architect"],
    "Strategy": ["Technical architect"],
    "Systems design": ["Frontend developer", "Infrastructure engineer", "Network architect", "Software developer", "Development operations (DevOps) engineer"],
    "Systems integration": ["Frontend developer", "Infrastructure engineer", "Software developer", "Development operations (DevOps) engineer"],
    "Systems integration (network architect)": ["Network architect"],
    "Team dynamics and collaboration": ["Delivery manager"],
    "Technical breadth": ["Quality Assurance Testing (QAT) analyst", "Test engineer", "Test manager"],
    "Technical specialism": ["End user computing engineer", "Infrastructure operations engineer", "Application operations engineer"],
    "Technical understanding": [
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Technical writer",
        "User researcher",
        "Application operations engineer",
        "Infrastructure engineer"
    ],
    "Technical understanding (data engineering)": ["Data engineer"],
    "Technical understanding (network architect)": ["Network architect"],
    "Technical understanding (performance analyst)": ["Performance analyst"],
    "Test analysis": ["Quality Assurance Testing (QAT) analyst", "Test engineer", "Test manager"],
    "Testing": ["Data engineer", "End user computing engineer", "Infrastructure operations engineer", "Application operations engineer", "Infrastructure engineer"],
    "Testing (business analysis)": ["Business analyst"],
    "Tools and software": ["Graphic design"],
    "Troubleshooting and problem resolution": ["Infrastructure engineer", "Network architect"],
    "Turning business problems into data design": ["Data architect"],
    "Turning business problems into technical design": ["Technical architect"],
    "Understanding analysys across the product lifecycle": ["Performance analyst"],
    "Understanding constraints (performance analyst)": ["Performance analyst"],
    "Understanding product delivery": ["Data scientist"],
    "Understanding security implications of transformation": ["Security architect"],
    "Understanding the whole context": ["Technical architect"],
    "Undertaking analysis and providing insight": ["Performance analyst"],
    "User focus": [
        "Application operations engineer",
        "Business relationship manager",
        "Change and release manager",
        "Command and control centre manager",
        "End user computing engineer",
        "Infrastructure operations engineer",
        "Incident manager",
        "IT service manager",
        "Problem manager",
        "Service desk manager",
        "Service transition manager",
        "Business analyst",
        "Product manager",
        "Service owner",
        "Frontend developer",
        "Software developer",
        "Content strategist",
        "Graphic designer",
        "Interaction designer",
        "Service designer",
        "Technical writer",
        "Development operations (DevOps) engineer"
    ],
    "User focus (content design)": ["Content designer"],
    "User-centred analysis": ["Performance analyst"],
    "User-centred and agile practices": ["User researcher"],
    "User-centred content design": ["Content designer", "Content strategist", "Technical writer"],
    "Verification and validation of data and analysis": ["Performance analyst"],
    "Web performance optimisation": ["Frontend developer"],
    "Working within constraints": ["Graphic designer", "Product manager"]
}

DDAT_JOB_TO_SKILLS_LOOKUP = reverse_dict_lists(DDAT_SKILLS_TO_JOB_LOOKUP)
