route:
  group_by: [Alertname]
  receiver: 'slack'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m

receivers:
  - name: 'slack'
    slack_configs:
    - send_resolved: true
      channel: 'notification-sandbox'
      api_url: ${METRICS_SLACK_WEBHOOK}

