global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
      - targets:
          - 'prometheus-alertmanager-i-dot-ai.apps.internal:8080'

scrape_configs:
  - job_name: 'i-dot-ai-exporter'
    static_configs:
      - targets:
          - prometheus-exporter-i-dot-ai.apps.internal:8080

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'localhost:8080'

  - job_name: 'monitoring_apps'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'localhost:8080'
          - 'prometheus-alertmanager-i-dot-ai.apps.internal:8080'
