---
applications:
- name: ellandi-api-develop
  services:
  - ellandi-postgres-develop
  routes:
  - route: ellandi-api-develop.london.cloudapps.digital
    protocol: http1
  processes:
  - type: web
    instances: 1
    memory: 128M
    disk_quota: 1024M
    health-check-type: port
