---
applications:
- name: ellandi-api-develop
  services:
  - ellandi-postgres-develop
  - scale-ellandi-api-develop
  routes:
  - route: ellandi-api-develop.london.cloudapps.digital
    protocol: http1
  - route: ellandi-api-develop.apps.internal
    protocol: http1
  processes:
  - type: web
    instances: 1
    memory: 1024M
    disk_quota: 8184M
    health-check-type: port
