---
applications:
  - name: ellandi-storybook-demo
    env:
      NODE_ENV: production
    routes:
      - route: ellandi-storybook-demo.london.cloudapps.digital
        protocol: http1
    processes:
      - type: web
        instances: 1
        memory: 128M
        disk_quota: 2048M
        health-check-type: port
