INITIAL_SKILLS = set(
    [
        "Academic engagement",
        "Behavioural insights",
        "Behavioural science",
        "Big data",
        "Business engagement",
        "Causal inference ",
        "Clinical trials",
        "Cloud computing",
        "Coaching",
        "Contract negotation",
        "Correspondence handling",
        "Crisis planning",
        "Data architecture",
        "Data engineering",
        "Data ethics",
        "Data science",
        "Data security",
        "Data visualisation",
        "Database management",
        "Delivery",
        "DevOps",
        "Diary management",
        "Diversity and inclusion",
        "Econometrics  ",
        "Economics ",
        "Evaluation",
        "Events management",
        "Excel",
        "Facilitation",
        "Facilities management",
        "Finance",
        "Frontline engagement",
        "Health and safety",
        "Helpdesk support",
        "HR",
        "Idea visualisation",
        "Influencing",
        "Innovation",
        "Intelligence",
        "Intelligence analysis",
        "Issues trees",
        "IT",
        "JavaScript",
        "Leadership",
        "Legal",
        "Linguistics",
        "Logistics",
        "Machine learning",
        "Marketing",
        "Mathematics",
        "Mediation",
        "Mentorship",
        "Military engineering",
        "Military experience",
        "National security",
        "Operations",
        "Pensions",
        "PHP",
        "Physics",
        "Policy",
        "Policy design",
        "Problem solving",
        "Procurement",
        "Programme evaluation ",
        "Programme management",
        "Programme targets and metrics",
        "Programming",
        "Project management",
        "Public speaking",
        "Public spending",
        "Python ",
        "Quality improvement",
        "Quantitive finance",
        "R",
        "Risk management",
        "Running workshops",
        "Scientific research",
        "Secretariating",
        "Semi-structured interviews",
        "Software development",
        "Software engineering",
        "Sports science",
        "Stakeholder management",
        "Stakeholder presentation",
        "Statistics ",
        "Strategy",
        "Survey design",
        "Tax",
        "Team management",
        "Training management",
        "Transformation",
        "User experience design",
        "User interface design",
        "Web analytics",
        "Key performance indicators",
        "Objectives and key results",
        "A/B testing",
        "Accounting",
        "Agile delivery",
        "Automation",
        "AWS",
        "Azure",
        "Business case development",
        "Change management",
        "Communications",
        "Content design",
        "Cyber security",
        "Digital marketing",
        "Engineering",
        "Geographic information systems",
        "Governance",
        "Dashboarding",
        "Interaction design",
        "Java",
        "Knowledge management",
        "Legislation",
        "Network management",
        "Operational research",
        "Options analysis",
        "Power BI",
        "PowerPoint",
        "Procurement",
        "Publication design",
        "Qualitative analysis",
        "Quantitative analysis",
        "Regulation",
        "Safety inspection",
        "Social research",
        "Software development",
        "SQL",
        "Strategy",
        "Version control",
        "Written communication",
        "Data",
        "Digital",
        "Analytical",
        "Finance (specifically counter-fraud)",
        "Commercial",
        "Policy",
        "Project delivery",
        "Leadership and line management",
        "Change management",
        "Crisis management",
        "Surge capability",
        "Secretariat",
    ]
)
