---
applications:
- name: organogram-sandbox
  services:
  - i-dot-ai-organogram-sandbox
  - organogram-postgres-sandbox
  routes:
  - route: organogram-sandbox.london.cloudapps.digital
    protocol: http1
  processes:
  - type: web
    instances: 1
    memory: 256M
    disk_quota: 1024M
    health-check-type: port
