# Generated by Django 3.2.13 on 2022-06-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_populate_orgs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractType",
            fields=[
                ("name", models.CharField(max_length=10)),
                ("slug", models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
