# Generated by Django 3.2.15 on 2022-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_loaddata_fixtures_langs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
