# Generated by Django 3.2.13 on 2022-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20220518_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('fixed_term', 'Fixed Term'), ('agency', 'Agency'), ('other', 'Other')], max_length=128, null=True),
        ),
    ]
