# Generated by Django 3.2.13 on 2022-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_populate_contract_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("name", models.CharField(max_length=10)),
                ("slug", models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
