# Generated by Django 3.2.15 on 2022-09-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_loaddata_fixtures_grades"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilllevel",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
