# Generated by Django 3.2.13 on 2022-05-30 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_weberror"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("modified_at", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("skill", models.CharField(choices=[("maths", "Maths"), ("python", "Python")], max_length=20)),
                (
                    "level",
                    models.CharField(
                        blank=True, choices=[("basic", "Basic"), ("proficient", "Proficient")], max_length=10
                    ),
                ),
                ("validated", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
