# Generated by Django 3.2.15 on 2022-09-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_loaddata_fixtures_skilllevels"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                ("name", models.CharField(max_length=127)),
                ("slug", models.CharField(max_length=127, primary_key=True, serialize=False)),
                ("order", models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
    ]
