# Generated by Django 3.2.13 on 2022-05-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20220530_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.AddField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registration.user'),
            preserve_default=False,
        ),
    ]
