# Generated by Django 3.2.13 on 2022-06-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_user_privacy_policy_agreement"),
        ("registration", "0009_auto_20220617_1307"),
    ]

    operations = []
