# Generated by Django 3.2.15 on 2022-09-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_alter_user_privacy_policy_agreement"),
        ("registration", "0009_loaddata_fixtures_jobtitles"),
    ]

    operations = []
