# Generated by Django 3.2.15 on 2022-09-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_loaddata_fixtures_jobtitles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privacy_policy_agreement',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
