# Generated by Django 3.2.15 on 2022-09-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_migrate_job_titles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ('slug',)},
        ),
    ]
