# Generated by Django 3.2.15 on 2022-09-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0010_alter_user_privacy_policy_agreement"),
        ("registration", "0010_merge_20220914_1936"),
    ]

    operations = []
