# Generated by Django 3.2.15 on 2022-09-20 18:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0011_merge_20220920_0645"),
    ]

    operations = [
        migrations.CreateModel(
            name="Learning",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "learning_type",
                    models.CharField(
                        choices=[("Work", "Work"), ("Social", "Social"), ("Formal", "Formal")],
                        editable=False,
                        max_length=31,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(null=True)),
                ("date_completed", models.DateField(null=True)),
                ("cost_pounds", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("cost_unknown", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
