# Generated by Django 3.2.13 on 2022-06-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_userskill_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='skill_name',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill_name')},
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='skill',
        ),
    ]
