# Generated by Django 3.2.13 on 2022-06-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0011_populate_grades_professions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privacy_policy_agreement",
            field=models.BooleanField(default=False),
        ),
    ]
