# Generated by Django 3.2.15 on 2022-09-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0012_learning"),
        ("registration", "0012_user_is_mentor"),
    ]

    operations = []
