# Generated by Django 3.2.15 on 2022-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0013_merge_0012_learning_0012_user_is_mentor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learning",
            name="learning_type",
            field=models.CharField(
                choices=[("On the job", "On the job"), ("Social", "Social"), ("Formal", "Formal")],
                editable=False,
                max_length=31,
            ),
        ),
    ]
