# Generated by Django 3.2.13 on 2022-06-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0013_alter_userskill_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model", models.CharField(max_length=100)),
            ],
        ),
    ]
