# Generated by Django 3.2.13 on 2022-06-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("registration", "0014_organisation"),
        ("registration", "0015_rename_model_organisation_organisation"),
        ("registration", "0017_auto_20220615_1356"),
    ]

    dependencies = [
        ("registration", "0013_alter_userskill_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("organisation", models.CharField(max_length=100)),
                ("org_slug", models.SlugField(default="", max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
