# Generated by Django 3.2.13 on 2022-06-16 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_userskill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='userskill',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='weberror',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
