# Generated by Django 3.2.13 on 2022-06-16 08:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0014_delete_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="userskill",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="weberror",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
