# Generated by Django 3.2.13 on 2022-06-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0015_userlanguage"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageSkillLevel",
            fields=[
                ("name", models.CharField(max_length=127)),
                ("slug", models.CharField(max_length=127, primary_key=True, serialize=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="contract_type",
            field=models.CharField(blank=True, default="", max_length=127),
            preserve_default=False,
        ),
    ]
