# Generated by Django 3.2.15 on 2022-09-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0015_user_is_self_reported_line_manager"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_self_reported_line_manager",
            new_name="is_line_manager",
        ),
    ]
