# Generated by Django 3.2.13 on 2022-06-16 08:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0015_auto_20220616_0825"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="id",
        ),
        migrations.RemoveField(
            model_name="weberror",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="weberror",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
