# Generated by Django 3.2.13 on 2022-06-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_rename_model_organisation_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_slug',
            field=models.SlugField(default='', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
