# Generated by Django 3.2.13 on 2022-06-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20220616_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userskill',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='weberror',
            old_name='temp_id',
            new_name='id',
        ),
    ]
