# Generated by Django 3.2.13 on 2022-06-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0016_auto_20220620_1255"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profession",
            field=models.ManyToManyField(to="registration.Profession"),
        ),
    ]
