# Generated by Django 3.2.13 on 2022-06-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0019_alter_organisation_org_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisation",
            old_name="organisation",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="organisation",
            old_name="org_slug",
            new_name="slug",
        ),
    ]
