# Generated by Django 3.2.13 on 2022-06-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0019_remove_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlanguage",
            name="type",
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
