# Generated by Django 3.2.15 on 2022-10-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0020_loaddata_fixtures_langskilllevels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlanguage",
            name="speaking_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Basic", "Basic"),
                    ("Independent", "Independent"),
                    ("Proficient", "Proficient"),
                    ("Native", "Native"),
                    ("None", "None"),
                ],
                max_length=127,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userlanguage",
            name="writing_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Basic", "Basic"),
                    ("Independent", "Independent"),
                    ("Proficient", "Proficient"),
                    ("Native", "Native"),
                    ("None", "None"),
                ],
                max_length=127,
                null=True,
            ),
        ),
    ]
