# Generated by Django 3.2.13 on 2022-06-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0021_alter_user_profession"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userlanguage",
            unique_together={("user", "language", "type")},
        ),
    ]
