# Generated by Django 3.2.14 on 2022-07-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0023_auto_20220705_2009"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebError",
        ),
    ]
