# Generated by Django 3.2.15 on 2022-10-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_loaddata_fixtures_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_token_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
