# Generated by Django 3.2.14 on 2022-07-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0024_delete_weberror"),
        ("registration", "0024_rename_usersalt_emailsalt"),
    ]

    operations = []
