# Generated by Django 3.2.15 on 2022-10-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='visibility',
        ),
    ]
