# Generated by Django 3.2.16 on 2022-10-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0027_remove_course_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="userskill",
            name="pending",
            field=models.BooleanField(default=False),
        ),
    ]
