# Generated by Django 3.2.16 on 2022-10-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0028_userskill_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="userskilldevelop",
            name="pending",
            field=models.BooleanField(default=False),
        ),
    ]
