# Generated by Django 3.2.16 on 2022-11-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_auto_20221102_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleRecommendation',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('recommended_skill', models.TextField(blank=True, db_column='recommendedSkill', null=True)),
                ('job_title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registration_titlerecommendation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkillRecommendation',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('recommended_skill', models.TextField(blank=True, db_column='recommendedSkill', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('current_skill', models.TextField(blank=True, db_column='currentSkill', null=True)),
            ],
        ),
    ]
