# Generated by Django 3.2.14 on 2022-07-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_user_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profession',
            new_name='professions',
        ),
    ]
