# Generated by Django 3.2.16 on 2022-11-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_skillrecommendation_titlerecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('recommended_skill', models.CharField(max_length=128)),
                ('source_type', models.CharField(choices=[('Job title', 'Job title'), ('Skill', 'Skill')], max_length=128)),
                ('source_value', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SkillRecommendation',
        ),
        migrations.DeleteModel(
            name='TitleRecommendation',
        ),
    ]
