# Generated by Django 3.2.16 on 2022-11-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0032_auto_20221107_1947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userskill",
            name="pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userskilldevelop",
            name="pending",
            field=models.BooleanField(default=True),
        ),
    ]
