# Generated by Django 3.2.16 on 2022-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0034_loaddata_fixtures_business_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="grades",
            field=models.JSONField(default=list),
        ),
    ]
