# Generated by Django 3.2.16 on 2022-11-16 10:30

from django.db import migrations, models

import ellandi.registration.models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0035_course_grades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="grades",
            field=models.JSONField(default=list, encoder=ellandi.registration.models.JSONSerializer),
        ),
    ]
