# Generated by Django 3.2.14 on 2022-07-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0031_rename_profession_user_professions"),
        ("registration", "0036_loaddata_fixtures"),
    ]

    operations = []
