# Generated by Django 3.2.16 on 2022-11-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0037_alter_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Blended", "Blended"),
                    ("Face-to-face", "Face-to-face"),
                    ("File", "File"),
                    ("Link", "Link"),
                    ("Video", "Video"),
                    ("Online course", "Online course"),
                ],
                max_length=256,
                null=True,
            ),
        ),
    ]
