# Generated by Django 3.2.14 on 2022-07-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0038_update_professions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contract_type_other",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="function",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="function_other",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="grade_other",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profession_other",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="languageskilllevel",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="contract_type",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="userlanguage",
            name="language",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="userlanguage",
            name="level",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="userlanguage",
            name="type",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("advanced_beginner", "Advanced Beginner"),
                    ("competent", "Competent"),
                    ("proficient", "Proficient"),
                    ("expert", "Expert"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
