# Generated by Django 3.2.14 on 2022-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0039_auto_20220729_1027"),
    ]

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[
                ("name", models.CharField(max_length=127)),
                ("slug", models.CharField(max_length=127, primary_key=True, serialize=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="business_unit",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location_other",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_profession",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
