# Generated by Django 3.2.16 on 2022-12-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0040_auto_20221201_2150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cost_pounds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="learning",
            name="cost_pounds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
