# Generated by Django 3.2.14 on 2022-07-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0040_auto_20220729_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_preference",
            field=models.BooleanField(default=False),
        ),
    ]
