# Generated by Django 3.2.16 on 2022-12-21 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ellandi.registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_loaddata_fixtures_business_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', ellandi.registration.models.LowercaseEmailField(max_length=254, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='first name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
