# Generated by Django 3.2.14 on 2022-08-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0042_add_functions_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_preference",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
