# Generated by Django 3.2.14 on 2022-08-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0043_auto_20220805_1730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userskill",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("advanced-beginner", "Advanced beginner"),
                    ("competent", "Competent"),
                    ("proficient", "Proficient"),
                    ("expert", "Expert"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
