# Generated by Django 3.2.14 on 2022-08-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0043_alter_user_contact_preference"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profession",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="profession",
            name="order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
