# Generated by Django 3.2.16 on 2022-12-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0043_invite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Sent", "Sent"), ("Accepted", "Accepted")],
                default="Pending",
                max_length=128,
            ),
        ),
    ]
