# Generated by Django 3.2.14 on 2022-08-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0044_alter_userskill_level"),
        ("registration", "0046_loaddata_fixtures"),
    ]

    operations = []
