# Generated by Django 3.2.14 on 2022-08-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0047_merge_20220808_1238"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlanguage",
            name="speaking_level",
            field=models.CharField(
                blank=True,
                choices=[("basic", "Basic"), ("independent", "Independent"), ("proficient", "Proficient")],
                max_length=127,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userlanguage",
            name="writing_level",
            field=models.CharField(
                blank=True,
                choices=[("basic", "Basic"), ("independent", "Independent"), ("proficient", "Proficient")],
                max_length=127,
                null=True,
            ),
        ),
    ]
