# Generated by Django 3.2.14 on 2022-08-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0048_auto_20220809_1454"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userlanguage",
            unique_together={("user", "language")},
        ),
        migrations.RemoveField(
            model_name="userlanguage",
            name="level",
        ),
        migrations.RemoveField(
            model_name="userlanguage",
            name="type",
        ),
    ]
