# Generated by Django 3.2.14 on 2022-08-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0049_auto_20220809_1457"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userlanguage",
            old_name="language",
            new_name="name",
        ),
        migrations.AlterUniqueTogether(
            name="userlanguage",
            unique_together={("user", "name")},
        ),
    ]
