# Generated by Django 3.2.14 on 2022-08-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0052_auto_20220810_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlanguage",
            name="speaking_level",
            field=models.CharField(
                blank=True,
                choices=[("Basic", "Basic"), ("Independent", "Independent"), ("Proficient", "Proficient")],
                max_length=127,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userlanguage",
            name="writing_level",
            field=models.CharField(
                blank=True,
                choices=[("Basic", "Basic"), ("Independent", "Independent"), ("Proficient", "Proficient")],
                max_length=127,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beginner", "Beginner"),
                    ("Advanced beginner", "Advanced beginner"),
                    ("Competent", "Competent"),
                    ("Proficient", "Proficient"),
                    ("Expert", "Expert"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
