# Generated by Django 3.2.14 on 2022-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0053_auto_20220811_0945"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillLevel",
            fields=[
                ("name", models.CharField(max_length=127)),
                ("slug", models.CharField(max_length=127, primary_key=True, serialize=False)),
                ("order", models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
