# Generated by Django 3.2.14 on 2022-08-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0055_loaddata_skilllevel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="languageskilllevel",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="languageskilllevel",
            name="order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="userlanguage",
            name="speaking_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Basic", "Basic"),
                    ("Independent", "Independent"),
                    ("Proficient", "Proficient"),
                    ("None", "None"),
                ],
                max_length=127,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userlanguage",
            name="writing_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Basic", "Basic"),
                    ("Independent", "Independent"),
                    ("Proficient", "Proficient"),
                    ("None", "None"),
                ],
                max_length=127,
                null=True,
            ),
        ),
    ]
