# Generated by Django 3.2.14 on 2022-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0056_auto_20220815_1751"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="organisation",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="country",
            name="order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="language",
            name="order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
