# Generated by Django 3.2.14 on 2022-08-17 14:27

from django.db import migrations
import ellandi.registration.models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0059_auto_20220816_1038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsalt",
            name="email",
            field=ellandi.registration.models.LowercaseEmailField(
                max_length=254, primary_key=True, serialize=False, unique=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=ellandi.registration.models.LowercaseEmailField(max_length=254, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="line_manager_email",
            field=ellandi.registration.models.LowercaseEmailField(blank=True, max_length=128, null=True),
        ),
    ]
