---
applications:
  - name: ellandi-api-temp
    services:
      - ellandi-postgres-temp
    routes:
      - route: ellandi-api-temp.london.cloudapps.digital
        protocol: http1
    processes:
      - type: web
        instances: 1
        memory: 256M
        disk_quota: 1024M
        health-check-type: port
