---
applications:
- name: ellandi-api-temp
  services:
  - ellandi-postgres-temp
  - scale-ellandi-api-temp
  routes:
  - route: ellandi-api-temp.london.cloudapps.digital
    protocol: http1
  processes:
  - type: web
    instances: 1
    memory: 1024M
    disk_quota: 4092M
    health-check-type: port
