---
applications:
- name: organogram-temp
  env:
    - name: DJANGO_SECRET_KEY
      value: ((django-secret-key))
  services:
  - i-dot-ai-organogram-temp
  - organogram-postgres-temp
  routes:
  - route: organogram-temp.london.cloudapps.digital
    protocol: http1
  processes:
  - type: web
    instances: 1
    memory: 128M
    disk_quota: 1024M
    health-check-type: port
