# Generated by Django 3.2.13 on 2022-05-25 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("users", models.ManyToManyField(blank=True, related_name="users", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
