name: Run Recommender App

on:
  # schedule:
  # - cron: '0 0 * * *'
  workflow_dispatch:
    branches:
      - temp
      - demo
      - sandbox
      - pentest
      - develop

jobs:
  cron_schedule:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [prod, staging]

    env:
      CF_SPACE: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v3


      - name: Download CF CLI
        if: success() || failure()
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx

      - name: CF login
        if: success() || failure()
        run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o co-i-ai -s "$CF_SPACE"

      - name: Trigger 'Non prod Recommender App task' api run
        if: ${{ success() && matrix.environment != 'prod' || failure() && matrix.environment != 'prod' }}
        run: ./cf run-task ellandi-recommender-"$CF_SPACE" --command "cd /app/recommender && python recommend.py" -k 8G

      - name: Trigger 'Prod Recommender App task' api run
        if: ${{ success() && matrix.environment == 'prod' || failure() && matrix.environment == 'prod' }}
        run: ./cf run-task ellandi-recommender --command "cd /app/recommender && python recommend.py" -k 8G
