name: Check backend code

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'bugfix/**'
      - 'develop'

jobs:
  check_backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        pip install -r api/requirements-dev.lock

    - name: Run Python Code Checks
      run: |
        make check-python-code

    - name: Run API Tests
      run: |
        make test-api

    - name: Run Organogram Tests
      run: |
        make test-organogram

    - uses: actions/checkout@v2
    - name: Slack Notification
      continue-on-error: true
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#FF0000'
        SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
        SLACK_TITLE: '${{ github.ref_name }} CodeCheck ${{ job.status }} :warning:'
        SLACK_USERNAME: ${{ github.actor }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'

  check_migrations:
    name: Check for missing migrations

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: make check-migrations

      - uses: actions/checkout@v2
      - name: Slack Notification
        continue-on-error: true
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
          SLACK_TITLE: '${{ github.ref_name }} CodeCheck ${{ job.status }} :warning:'
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'

  check_frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: 'web/package-lock.json'

      - run: cd web && npm install

      - run: make validate-frontend

      - uses: actions/checkout@v2
      - name: Slack Notification
        continue-on-error: true
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
          SLACK_TITLE: '${{ github.ref_name }} CodeCheck ${{ job.status }} :warning:'
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'
