name: Deploy

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - sandbox
      - temp
      - develop
      - prod

permissions:
  packages: write
  repository-projects: read
  id-token: write
  contents: read


jobs:
  push_images:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name }}
      DOCKER_REPOSITORY: ghcr.io
      NODE_ENV: development
      CF_SPACE: ${{ github.ref_name }}
      NEXT_PUBLIC_API_URL: https://ellandi-api-${{ github.ref_name }}.london.cloudapps.digital

    strategy:
      matrix:
        app: [ellandi-api, ellandi-web, organogram]
        include:
          - app: ellandi-api
            dockerfile: docker/api/Dockerfile
          - app: ellandi-web
            dockerfile: docker/web/Dockerfile
          - app: organogram
            dockerfile: docker/organogram/Dockerfile

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push ${{ matrix.app }} image
        env:
          DOCKER_FILE: ${{ matrix.dockerfile }}
          DOCKER_IMAGE: ${{ matrix.app }}

        run: |
          docker build . --file $DOCKER_FILE --tag $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --build-arg NODE_ENV=$NODE_ENV --build-arg NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
          docker push -a $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE

  deploy_image:
    needs: [push_images]

    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name }}
      DOCKER_REPOSITORY: ghcr.io
      CF_SPACE: ${{ github.ref_name }}

    strategy:
      matrix:
        app: [ellandi-api, ellandi-web, organogram]

    steps:
      - uses: actions/checkout@v3

      - name: Download CF CLI
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx

      - name: CF login
        run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o co-i-ai -s "$CF_SPACE"

      - name: CF push ellandi apps
        if: ${{ matrix.app == 'ellandi-api' || matrix.app == 'ellandi-web' }}
        env:
          DOCKER_FILE: ${{ matrix.dockerfile }}
          DOCKER_IMAGE: ${{ matrix.app }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: CF_DOCKER_PASSWORD="$GITHUB_TOKEN" ./cf push -f manifests/"$CF_SPACE/${{ matrix.app }}"_manifest.yml --docker-image $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --docker-username=$GITHUB_ACTOR


      - name: CF push organogram non-production
        if: ${{ matrix.app == 'organogram' && github.ref_name != 'prod' }}
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DOCKER_FILE: ${{ matrix.dockerfile }}
          DOCKER_IMAGE: ${{ matrix.app }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          echo $DOCKER_IMAGE:$IMAGE_TAG
          CF_DOCKER_PASSWORD="$GITHUB_TOKEN" ./cf push -f manifests/"$CF_SPACE/${{ matrix.app }}"_manifest.yml --var django-secret-key=${{ env.DJANGO_SECRET_KEY }} --docker-image $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --docker-username=$GITHUB_ACTOR

      - name: CF push organogram production
        if: ${{ matrix.app == 'organogram' && github.ref_name == 'prod' }}
        env:
          DOCKER_FILE: ${{ matrix.dockerfile }}
          DOCKER_IMAGE: ${{ matrix.app }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: CF_DOCKER_PASSWORD="$GITHUB_TOKEN" ./cf push -f manifests/"$CF_SPACE/${{ matrix.app }}"_manifest.yml --docker-image $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --docker-username=$GITHUB_ACTOR
