name: Deploy develop

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    # Publish `develop` as Docker `latest` image.
    branches:
      - feature/playwrite-python

permissions:
  packages: write
  repository-projects: read
  id-token: write
  contents: read

jobs:
  check_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -U pyinstaller playwright
          playwright install-deps
          playwright install chromium

      - name: build tests
        run: |
          make playwright-test
