---
name: Test

on:
  push:
    branches:
      - sandbox


permissions:
  packages: write
  repository-projects: read
  id-token: write
  contents: read


jobs:
  deploy_proxy:

    runs-on: ubuntu-latest

    env:
      CF_SPACE: ${{ github.ref_name }}

    strategy:
      matrix:
        app: [ellandi-api, ellandi-web, organogram]

    steps:
      - uses: actions/checkout@v3

      - name: Download CF CLI
        working-directory: ./proxy
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx

      - name: CF login
        working-directory: ./proxy
        run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o co-i-ai -s "$CF_SPACE"

      - name: CF push proxy apps non-prod
        if: ${{ matrix.app == 'organogram' && github.ref_name != 'prod' }}
        env:
          APP_NAME: ${{ matrix.app }}
          PROTECTED_APP_NAME: ${{ matrix.app }}-${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          ROUTE_SERVICE_APP_NAME:
        working-directory: ./proxy
        run: |
