---
name: Test

on:
  push:
    branches:
      - sandbox


permissions:
  packages: write
  repository-projects: read
  id-token: write
  contents: read


jobs:
  deploy_proxy:

    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name }}
      DOCKER_REPOSITORY: ghcr.io
      CF_SPACE: ${{ github.ref_name }}

    strategy:
      matrix:
        app: [ellandi-api, ellandi-web, organogram]

    steps:
      - uses: actions/checkout@v3

      - name: Download CF CLI
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx

      - name: CF login
        run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o co-i-ai -s "$CF_SPACE"

      - name: CF push ellandi apps
        if: ${{ matrix.app == 'ellandi-api' || matrix.app == 'ellandi-web' }}
        env:
          APP_NAME: ${{ matrix.app }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          ./echo $APP_NAME
          ./cf app $APP_NAME
