name: Deploy develop

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    # Publish `develop` as Docker `latest` image.
    branches:
      - sandbox

jobs:

  push_images:

    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: latest
      DOCKER_REPOSITORY: singletoned

    strategy:
      matrix:
        app: [ ellandi-api, ellandi-web ]
        include:
          - app: ellandi-api
            dockerfile: docker/api/Dockerfile
          - app: ellandi-web
            dockerfile: docker/web/Dockerfile

    steps:
      - uses: actions/checkout@v3

      - name: Login
        env:
          CF_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          CF_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$CF_DOCKER_PASSWORD" | docker login -u $CF_DOCKER_USERNAME --password-stdin registry-1.docker.io

      - name: Build, tag, and push ${{ matrix.app }} image
        env:
          CF_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CF_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_FILE: ${{ matrix.dockerfile }}
          DOCKER_IMAGE: ${{ matrix.app }}

        run: |
          docker build . --file $DOCKER_FILE --tag $DOCKER_REPOSITORY/$DOCKER_IMAGE:$IMAGE_TAG
          docker push $DOCKER_REPOSITORY/$DOCKER_IMAGE:$IMAGE_TAG

  deploy_sandbox:

    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: latest
      DOCKER_REPOSITORY: singletoned

    strategy:
      matrix:
        app: [ ellandi-api, ellandi-web ]

    steps:
      - name: Donwload CF CLI
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx

      - name: CF login
        run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o cabinet-office-data-assets-catalogue -s develop

      - name: CF push ${{ matrix.app }}
        env:
          CF_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          CF_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_FILE: ${{ matrix.dockerfile }}
          DOCKER_IMAGE: ${{ matrix.app }}
        run: CF_DOCKER_PASSWORD=$"CF_DOCKER_PASSWORD" ./cf push "${{ matrix.app }}" --docker-image $DOCKER_REPOSITORY/$DOCKER_IMAGE:$IMAGE_TAG --docker-username=$CF_DOCKER_USERNAME
