---
name: Slack Notification Test

on:
  push:
    branches:
      - sandbox

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - name: Step to fail
      run: curl -L "https://localhost:8080/fail"

    - uses: actions/checkout@v2
    - name: Slack Notification
      continue-on-error: true
      if: ${{ failure() && github.ref_name == 'prod' || github.ref_name == 'sandbox' }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#FF0000'
        SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
        SLACK_TITLE: '${{ github.ref_name }} deployment ${{ job.status }} :warning:'
        SLACK_USERNAME: ${{ github.actor }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'
