name: Deploy Storybook

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - sandbox
      - develop
      - temp
      - demo
    paths:
      - .github/workflows/storybook.yml
      - 'docker/storybook/Dockerfile'
      - 'manifests/*/ellandi-storybook_manifest.yml'
      - 'web/.storybook/**'
      - 'web/*.stories.tsx'
      - 'web/*.tsx'

permissions:
  packages: write
  repository-projects: read
  id-token: write
  contents: read

jobs:
  push_images:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name }}
      DOCKER_REPOSITORY: ghcr.io
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push ellandi-storybook image
        env:
          DOCKER_FILE: docker/storybook/Dockerfile
          DOCKER_IMAGE: ellandi-storybook

        run: |
          docker build . --file $DOCKER_FILE --tag $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG
          docker push -a $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE


  deploy_image:
    needs: [push_images]

    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name }}
      DOCKER_REPOSITORY: ghcr.io

    steps:
      - uses: actions/checkout@v3

      - name: Get space name
        uses: kanga333/variable-mapper@master
        with:
          key: "${{github.ref_name}}"
          map: |
            {
              "demo": {"CF_SPACE": "demo"},
              "temp": {"CF_SPACE": "temp"},
              "develop": {"CF_SPACE": "develop"},
              "main": {"CF_SPACE": "prod"},
              "feature/deploy-from-main": {"CF_SPACE": "flibble"}
            }

      - name: Download CF CLI
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx

      - name: CF login
        run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o co-i-ai -s "$CF_SPACE"

      - name: CF push ellandi-storybook
        env:
          DOCKER_IMAGE: ellandi-storybook
          PAT_TOKEN_USER: ${{ secrets.PAT_TOKEN_USER }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: CF_DOCKER_PASSWORD="$PAT_TOKEN" ./cf push -f manifests/"$CF_SPACE/ellandi-storybook"_manifest.yml --docker-image $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --docker-username=$PAT_TOKEN_USER

      - uses: actions/checkout@v2
      - name: Slack Notification
        continue-on-error: true
        if: ${{ failure() && github.ref_name == 'prod' || failure() && github.ref_name == 'develop' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
          SLACK_TITLE: '${{ github.ref_name }} deployment ${{ job.status }} :warning:'
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'


  deploy_proxy:
    needs: deploy_image
    runs-on: ubuntu-latest

    env:
      CF_SPACE: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Download CF CLI
        working-directory: ./proxy
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx

      - name: CF login
        working-directory: ./proxy
        run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o co-i-ai -s "$CF_SPACE"

      - name: Get IPs
        id: get_ips
        working-directory: ./proxy
        run: echo "::set-output name=ips::$(tr '\n' ' ' <whitelisted_ips.txt)"

      - name: CF push proxy app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          ROUTE_SERVICE_APP_NAME: ellandi-storybook-proxy-${{ env.CF_SPACE }}
          ROUTE_SERVICE_NAME: ellandi-storybook-route-${{ env.CF_SPACE }}
          PROTECTED_APP_NAME: ellandi-storybook-${{ env.CF_SPACE }}
          ALLOWED_IPS: ${{ steps.get_ips.outputs.ips }}
        working-directory: ./proxy
        run: |
            ./proxy-deploy.sh

      - uses: actions/checkout@v2
      - name: Slack Notification
        continue-on-error: true
        if: ${{ failure() && github.ref_name == 'prod' || failure() && github.ref_name == 'develop' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
          SLACK_TITLE: '${{ github.ref_name }} deployment ${{ job.status }} :warning:'
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'
